build/project-template/__PROJECT_NAME__/__PROJECT_NAME__-Info.plist
We need this for nativescript cli
=> Add placeholder for CFBundleIdentifier

src/NativeScript/NativeScript/ObjCConstructorBase.mm
Otherwise we wrap their wrappers in adapters and stuff gets broken
=> Properly unbox NSArray and NSDictionary instances

gruntfile.js, package.json
Add the code to increase the package version and retrieve/add the commit SHA to package.json
=> Add build and commit information to package.json

gruntfile.js
=> Add the NativeScript.framework to the tns-ios

src/debugging/TNSDebugging.h
http://fuckingclangwarnings.com/
=> Disable possible retain cycle warning in TNSDebugging.h

build/project-template/__PROJECT_NAME__/main.m
https://github.com/NativeScript/nativescript-cli/issues/523
=> LiveSync support

build/scripts/WIBuildForChrome.sh, src/debugging/WebInspectorUI/Base/Object.js, src/debugging/WebInspectorUI/Views/CallFrameView.js, src/debugging/WebInspectorUI/Views/ResourceSidebarPanel.js, src/debugging/polyfills.js
Would implement this https://github.com/NativeScript/ios-runtime/issues/163
=> Update the script that would be used to generate Web Inspector frontend for Chrome 

build/project-template/__PROJECT_NAME__.xcodeproj/project.pbxproj
We need this in order to fix this issue - https://github.com/NativeScript/nativescript-cli/issues/520
=> Add Resources group and move all images inside it

src/NativeScript/Calling/FFICall.cpp, src/NativeScript/Calling/FFICall.h, src/NativeScript/Calling/FFIFunctionCall.h, src/NativeScript/Calling/FFIFunctionCall.mm, src/NativeScript/ObjC/Block/ObjCBlockCall.h, src/NativeScript/ObjC/Block/ObjCBlockCall.mm, src/NativeScript/ObjC/Constructor/ObjCConstructorCall.h, src/NativeScript/ObjC/Constructor/ObjCConstructorCall.mm, src/NativeScript/ObjC/ObjCMethodCall.h, src/NativeScript/ObjC/ObjCMethodCall.mm, tests/TestFixtures/TNSTestNativeCallbacks.h, tests/TestFixtures/TNSTestNativeCallbacks.m, tests/TestRunner/app/MethodCallsTests.js
=> Recursive method calls 2

src/NativeScript/Calling/FFICall.cpp, src/NativeScript/Calling/FFICall.h, src/NativeScript/Calling/FFICallback.h, src/NativeScript/Metadata/Metadata.h, src/NativeScript/ObjC/ObjCMethodCall.h, src/NativeScript/ObjC/ObjCMethodCall.mm, src/NativeScript/ObjC/ObjCMethodCallback.h, src/NativeScript/ObjC/ObjCMethodCallback.mm, src/NativeScript/TypeFactory.mm, tests/TestFixtures/Api/TNSApi.h, tests/TestFixtures/Api/TNSApi.m, tests/TestFixtures/TNSTestNativeCallbacks.h, tests/TestFixtures/TNSTestNativeCallbacks.m, tests/TestRunner/app/ApiTests.js
=> Throw NSError as JS error

src/debugging/TNSDebugging.h
https://github.com/NativeScript/ios-runtime/issues/189
=> Add notifications so that clients will know when the app is going to resign or become active

src/NativeScript/TNSRuntime.mm
=> Handle memory pressure on iOS

src/NativeScript/TNSRuntime.mm
Removing an observer added with
`-[NSNotificationCenter addObserverForName:object:queue:usingBlock:]` crashes. Replace with the old, boring `-[NSNotificationCenter addObserver:selector:name:object:]` instead.
Fixes #229
=> Remove NSNotificationCenter blocks-based API usage

src/NativeScript/JSWarnings.cpp
Right now JSGlobalObjectConsoleClient::logWithLevel() can crash when there is no top call frame when called from NativeScript::warn
=> Work around crash when logging warnings

src/NativeScript/require.js
Related to: https://github.com/NativeScript/NativeScript/issues/545
=> Require from home folder relative to app

build/project-template/__PROJECT_NAME__.xcodeproj/project.pbxproj
Fixes https://github.com/NativeScript/nativescript-cli/issues/777
=> Add lib/iOS folder to framework search paths

CHANGELOG.md, package.json
=> Prepare for v1.2.3

src/NativeScript/inspector/SourceProviderManager.cpp
=> File ending with a commented line bugfix

src/NativeScript/JSErrors.mm, src/NativeScript/ObjC/Inheritance/ObjCTypeScriptExtend.mm
https://github.com/NativeScript/ios-runtime/issues/78
=> Call global.__onUncaughtError if a fatal exception is thrown

src/NativeScript/GlobalObject.mm, src/NativeScript/ObjC/ObjCPrimitiveTypes.mm, tests/TestFixtures/Api/TNSDeclarationConflicts.h, tests/TestFixtures/Api/TNSDeclarationConflicts.m, tests/TestFixtures/CMakeLists.txt, tests/TestFixtures/TestFixtures.h, tests/TestFixtures/exported-symbols.txt, tests/TestRunner/app/DeclarationConflicts.js, tests/TestRunner/app/bootstrap.js
Merge after: https://github.com/NativeScript/ios-metadata-generator/pull/18
=> Disambiguate native APIs with name collisions

build/project-template/__PROJECT_NAME__.xcodeproj/project.pbxproj
This would leave CocoaPods xcconfig.
=> Move build.xcconfig to Project

build/project-template/__PROJECT_NAME__/main.m, cmake/main.m, examples/BlankApp/main.m, src/NativeScript/GlobalObject.h, src/NativeScript/GlobalObject.mm, src/NativeScript/TNSRuntime.h, src/NativeScript/TNSRuntime.mm, tests/TestRunner/app/Promises.js, tests/TestRunner/app/bootstrap.js
=> Schedule the runtime on the runloop of its owner thread

examples/Gameraww/app/MasterViewController.js
=> indexPathForSelectedRow changed to property

build/scripts/metadata-generation-build-step, tests/TestRunner/app/ApiTests.js
Merge after https://github.com/NativeScript/ios-metadata-generator/pull/24
Merge after configuring Clang 3.7 to build machines.
=> Migrate to Clang 3.7

build/project-template/internal/main.m, build/project-template/internal/nativescript-build.xcconfig
https://github.com/CocoaPods/CocoaPods/issues/1761
=> Fix cocoapods xcconfig flags conflicts

build/project-template/internal/nativescript-build.xcconfig
=> Add internal folder to header search paths

src/NativeScript/CMakeLists.txt, src/NativeScript/Calling/FFICall.cpp, src/NativeScript/Calling/FFICall.h, src/NativeScript/Calling/FFICallPrototype.cpp, src/NativeScript/Calling/FFICallPrototype.h, src/NativeScript/Calling/FFIFunctionCall.h, src/NativeScript/Calling/FFIFunctionCall.mm, src/NativeScript/GlobalObject.h, src/NativeScript/GlobalObject.mm, src/NativeScript/ObjC/Block/ObjCBlockCall.h, src/NativeScript/ObjC/Block/ObjCBlockCall.mm, src/NativeScript/ObjC/Constructor/ObjCConstructorBase.mm, src/NativeScript/ObjC/Constructor/ObjCConstructorCall.h, src/NativeScript/ObjC/Constructor/ObjCConstructorCall.mm, src/NativeScript/ObjC/ObjCMethodCall.h, src/NativeScript/ObjC/ObjCMethodCall.mm, src/NativeScript/Runtime/ReleasePool.h, tests/TestRunner/app/ApiTests.js
=> Add async method to FFICall

src/NativeScript/GlobalObject.mm, tests/TestFixtures/Api/TNSApi.h, tests/TestRunner/app/ApiTests.js
I want to merge this in the release branch, if possible. The QAs are fine with that.
=> Throw error if there is a metadata for a symbol, but it's not available at runtime

tests/TestFixtures/Api/TNSBridgedTypes.h, tests/TestFixtures/Api/TNSBridgedTypes.m, tests/TestFixtures/CMakeLists.txt, tests/TestFixtures/TestFixtures.h, tests/TestFixtures/exported-symbols.txt, tests/TestRunner/app/ApiTests.js, tests/TestRunner/app/Marshalling/ObjCTypesTests.js
Merge with: https://github.com/NativeScript/ios-metadata-generator/pull/27/
=> Add more bridged types

build/project-template/__PROJECT_NAME__/build-debug.xcconfig, build/project-template/__PROJECT_NAME__/build-release.xcconfig
https://github.com/NativeScript/nativescript-cli/pull/1042
=> Include merged xcconfig files from CLI

src/debugging/Inspector/Inspector/NativeScript Inspector/InspectorFrontendHost.h, src/debugging/Inspector/Inspector/NativeScript Inspector/InspectorFrontendHost.m, src/debugging/Inspector/Inspector/NativeScript Inspector/InspectorFrontendHostProtocol.h
=> Fix Inspector window dragging on El Capitan

build/scripts/build.sh, cmake/CreateNativeScriptApp.cmake, gruntfile.js, src/NativeScript/CMakeLists.txt
Reverts NativeScript/ios-runtime#343
=> Revert "Generate dSYM for NativeScript.framework"

build/project-template/internal/nativescript-build.xcconfig
=> Escape any potential spaces in build setting paths

CHANGELOG.md
=> 1.5 changelog

src/NativeScript/TNSRuntime.mm, src/NativeScript/inlineFunctions.js
Use [ES6 shorthand property names](http://ariya.ofilabs.com/2013/02/es6-and-object-literal-property-value-shorthand.html)
=> Refactor inline functions

src/NativeScript/inspector/DomainBackendDispatcher.cpp, src/NativeScript/inspector/DomainBackendDispatcher.h, src/NativeScript/inspector/DomainInspectorAgent.cpp, src/NativeScript/inspector/DomainInspectorAgent.h, src/NativeScript/inspector/GlobalObjectInspectorController.cpp, src/NativeScript/inspector/GlobalObjectInspectorController.h
We use to wait for didCreateFrontendAndBackend to get the frontend and backend in the domain agents but now a null pointers are passed so use a JSAgentContext instead.
=> Use JSAgentContext as all the other agents

.gitignore, build/scripts/build-inspector.sh, gruntfile.js, src/debugging/Inspector/Inspector/.gitignore, src/debugging/Inspector/Inspector/Inspector.xcodeproj/project.pbxproj, src/debugging/Inspector/Inspector/Inspector.xcodeproj/xcshareddata/xcschemes/Inspector.xcscheme, src/debugging/Inspector/Inspector/export-options.plist
@KristinaKoeva, could you give a hand with the code signing?
This should add no more than a minute to the build time (except the first time).
=> Add inspector build script

build/project-template/internal/nativescript-build.xcconfig
=> Remove quotes from paths in nativescript-build.xcconfig

src/NativeScript/ObjC/Inheritance/ObjCTypeScriptExtend.mm, tests/TestRunner/app/Inheritance/TypeScriptTests.js, tests/TestRunner/app/Inheritance/TypeScriptTests.ts
=> TypeScript extends should not replace parent scope variables 

src/NativeScript/require.js
=> Throw an error if loading module source fails

src/NativeScript/require.js
https://github.com/NativeScript/ios-runtime/issues/450
=> Throw error if package.json has non-utf8 encoding

tests/TestRunner/app/index.js
https://github.com/NativeScript/common-runtime-tests-app/pull/12
=> Remove iOS specifics in common require test

src/NativeScript/require.js
https://github.com/NativeScript/common-runtime-tests-app/pull/13
https://github.com/NativeScript/common-runtime-tests-app/pull/14
https://github.com/NativeScript/common-runtime-tests-modules/pull/1
=> Update shared tests

src/NativeScript/ObjC/Inheritance/ObjCClassBuilder.mm, tests/TestRunner/app/Inheritance/InheritanceTests.js
Close https://github.com/NativeScript/ios-runtime/issues/451.
=> Rename Objective-C class name in case of extend conflicts

src/NativeScript/GlobalObject.h, src/NativeScript/GlobalObject.moduleLoader.mm, tests/TestFixtures/TNSTestCommon.m
=> Fix module resolution to more closely follow Node's

build/project-template/internal/main.m
This improves the startup time of the hello-world project from 1311ms seconds to 813ms :cat:
=> Use proper debug macro in project template.

src/NativeScript/TNSRuntime.mm
Close https://github.com/NativeScript/ios-runtime/issues/493
ping @vchimev
=> Normalize application path as require.js did

build/project-template/__PROJECT_NAME__/build.xcconfig
Releated to: https://github.com/NativeScript/nativescript-cli/pull/1448
=> Remove code signing identity from project template

src/NativeScript/ObjC/Constructor/ObjCConstructorBase.h, src/NativeScript/TypeFactory.mm
Probably related to: https://github.com/NativeScript/ios-runtime/issues/259
=> Fix memory crashes

src/NativeScript/ObjC/Constructor/ObjCConstructorBase.mm
=> CString fix

LICENSE
Related to: https://github.com/NativeScript/NativeScript/pull/1786
ping @ErjanGavalji
=> Fix the license agreements

src/NativeScript/GlobalObject.moduleLoader.mm, tests/TestRunner/app/Modules/WindowsEncoding.js, tests/TestRunner/app/Modules/index.js, tests/TestRunner/app/index.js
Closes https://github.com/NativeScript/ios-runtime/issues/539
=> Throw error on unknown module character encoding

build/scripts/build-inspector.sh, build/scripts/get_version.py, build/scripts/update-version.py, src/debugging/Inspector/Inspector/NativeScript Inspector/Info.plist
=> Retrieve inspector version from package.json

CMakeLists.txt, build/scripts/build-inspector.sh, src/NativeScript/CMakeLists.txt, src/NativeScript/GlobalObject.mm
Related to:
* https://github.com/NativeScript/android-runtime/pull/428
* https://github.com/NativeScript/common-runtime-tests-app/pull/17
=> Add runtime version variable to the global object

CHANGELOG.md
CHANGELOG text styling improvements done by @erikruth in the docs repo applied to the origin of the article.
No tests, textual content improvements only.
=> Apply changelog styling changes by Erik

plugins/TKLiveSync/TKLiveSync/TKLiveSync.m
The application is displaying a black screen for 15 seconds at worst.
ping @tzraikov
=> Report to the user that LiveSync contents is being unzipped

build/project-template/internal/nativescript-build.xcconfig
https://pewpewthespells.com/blog/xcconfig_guide.html#CondVarConfig
=> Fix linking livesync framework

src/NativeScript/CMakeLists.txt
Fixes https://github.com/NativeScript/ios-runtime/issues/595
=> Export more symbols from the NativeScript framework

CMakeLists.txt, build/scripts/metadata-generation-build-step, tests/TestFixtures/Api/TNSApi.m, tests/TestRunner/app/ApiTests.js, tests/TestRunner/app/MetadataTests.js
Includes related changes from: https://github.com/NativeScript/ios-runtime/pull/456
=> Backport tvOS fixes

README.md
CMake 3.1 from Brew has some problems during installation.
ping @pkoleva
=> Use prebuilt CMake in README.md

src/NativeScript/ObjC/Block/ObjCBlockType.mm, tests/TestFixtures/Marshalling/TNSObjCTypes.m, tests/TestRunner/app/Marshalling/ObjCTypesTests.js
=> Marshall nil block type as JS null

README.md
build/script/ path does not exist.
=> Corrected the build/scripts/ path

build/scripts/build-runtime.sh
Closes https://github.com/NativeScript/ios-runtime/issues/651.
=> Add README.md to npm package

README.md, examples/Gameraww/app/CanvasViewController.js, examples/Gameraww/app/MasterViewController.js, examples/Gameraww/app/fetch.js, tests/TestFixtures/Interfaces/TNSMethodCalls.h, tests/TestFixtures/Interfaces/TNSMethodCalls.m, tests/TestRunner/app/ApiTests.js, tests/TestRunner/app/Inheritance/InheritanceTests.js, tests/TestRunner/app/Marshalling/ObjCTypesTests.js, tests/TestRunner/app/MethodCallsTests.js, tests/TestRunner/app/VersionDiffTests.js, tests/TestRunner/app/index.js
Related:
* https://github.com/NativeScript/ios-runtime-docs/pull/54
* Tests for https://github.com/NativeScript/ios-runtime/pull/635
Requires Xcode 8
=> Update to Xcode 8 class properties

src/NativeScript/TypeFactory.mm
This happens only in our synthetic tests with the `GCController` class.
This happens when running our tests building with the iOS 10 SDK and running it on an older one.
=> Handle conflicting availability

src/debugging/WebInspectorUI/Views/FileSystemRepresentationTreeElement.js
onpopulate is called many times now
=> Fix inspector showing sources multiple times

src/NativeScript/Interop.h, src/NativeScript/Interop.mm, src/NativeScript/ObjC/Enumeration/TNSFastEnumerationAdapter.mm, src/NativeScript/ObjC/Inheritance/ObjCClassBuilder.mm, src/NativeScript/ObjC/ObjCTypes.mm, src/NativeScript/ObjC/ObjCWrapperObject.mm, src/NativeScript/ObjC/TNSArrayAdapter.mm, src/NativeScript/ObjC/TNSDataAdapter.mm, src/NativeScript/ObjC/TNSDictionaryAdapter.mm, src/NativeScript/TNSRuntime+Private.h, src/NativeScript/TNSRuntime.mm
TNSArrayAdapter, TNSDataAdapter and TNSDictionaryAdapter can be deallocated after TNSRuntime deallocation without crashing
=> Adapters deallocation fix

tests/TestFixtures/TNSTestCommon.h, tests/TestFixtures/TNSTestCommon.m, tests/TestFixtures/exported-symbols.txt, tests/TestRunner/app/ApiTests.js
Hide some tests behind a flag because they are expected to fail if the tests are built for release.
=> Disable some tests in release

src/NativeScript/CMakeLists.txt, src/NativeScript/inspector/GlobalObjectConsoleClient.cpp, src/NativeScript/inspector/GlobalObjectConsoleClient.h, src/NativeScript/inspector/GlobalObjectInspectorController.cpp, src/NativeScript/inspector/InspectorLogAgent.cpp, src/NativeScript/inspector/InspectorLogAgent.h
Merge with https://github.com/NativeScript/webkit/pull/14.
=> Chrome Dev Tools decided to name the agent responsible for the Console - Log Agent, so say hello to the Log Agent.

build/project-template/internal/nativescript-build.xcconfig
https://github.com/NativeScript/nativescript-cli/pull/2195
=> remove '/../../lib/iOS' from framework search paths

build/project-template/__PROJECT_NAME__.xcodeproj/project.pbxproj
Reverts NativeScript/ios-runtime#743
=> Revert "Hot fix for AppIcon in the pbxproj template file for the current 2.5.…"

build/project-template/__PROJECT_NAME__.xcodeproj/project.pbxproj, src/NativeScript/inlineFunctions.js, tests/TestRunner/app/Inheritance/TypeScriptTests.js, tests/TestRunner/app/Inheritance/TypeScriptTests.ts
Implements #754 
Related PRs:
* Core modules: https://github.com/NativeScript/NativeScript/pull/4048
* Docs: https://github.com/NativeScript/ios-runtime-docs/pull/61
=> ObjC TS decorators for specifying protocols and exposed methods

build/project-template/internal/main.m, build/project-template/internal/nativescript-build.xcconfig, build/project-template/internal/nativescript-post-build, build/scripts/build-livesync-framework.sh, build/scripts/build-livesync-static-lib.sh, build/scripts/package-tns-ios.sh, plugins/TKLiveSync/Podfile, plugins/TKLiveSync/Podfile.lock, plugins/TKLiveSync/TKLiveSync.xcodeproj/project.pbxproj, plugins/TKLiveSync/TKLiveSync.xcworkspace/contents.xcworkspacedata, plugins/TKLiveSync/TKLiveSync/TKLiveSync.h, plugins/TKLiveSync/TKLiveSync/TKLiveSync.m
Fixes: https://github.com/NativeScript/ios-runtime/issues/746
=> Restart app on livesync

src/NativeScript/JSErrors.mm
* NSLog writes to both the Apple System Log and stderr. The change is necessary
because CLI watches ASL for messages
* CLI's parser cannot parse multi-line messages and we need to rewrite it. Meanwhile
we can workaround it by calling NSLog once for every line being logged.
fixes #565
=> fix(runtime): Use NSLog for dumping each line of callstack on crash

src/NativeScript/GlobalObject.moduleLoader.mm
=> Cherry-pick: Fixes issues with resolution of canonical paths

src/debugging/TNSDebugging.h
Schedule check for existing frontend client 30 sec. after opening socket or disconnecting the frontend. This is necessary because all {N} apps use one and the same port for debugging communication (18181). If we don't free it as soon as we're finished with the debugger, no other {N} app will be able to do LiveSync or be debugged on the same device.
=> fix(inspector): Close debugging port when it's not used

CHANGELOG.md, build/npm/inspector_package.json, build/npm/runtime_package.json
As discussed, version is reverted to 3.4.1.
=> Version update

src/debugging/TNSDebugging.h
Closing dispatch channel is asynchronous and creating the new server can sporadically fail.
Instead of closing it we can safely reuse it by ensuring that it won't be destroyed from an
already started cleanup timer. We're just moving the `scheduleCleanup` call before checking
whether there's an existing `listenSource` and dropping the connection to any already attached
frontend inspector.
=> fix(inspector): Do not close and reopen listening source on "AttachRequest"

build/scripts/package-tns-ios-inspector.sh
The $BINARIES_DIR will be defined by the build itself.
=> chore: Update package script to copy already built binaries.

.github/issue_template.md, .github/pull_request_template.md, README.md
- add PR and issue template
- add Contribute section in Readme
=> docs: add PR and issue template, update readme

build/npm/inspector_package.json, build/npm/runtime_package.json
=> Bump version

build/npm/inspector_package.json, build/npm/runtime_package.json
=> chore: Bump versions to 4.1.1

build/npm/inspector_package.json, build/npm/runtime_package.json, src/debugging/TNSDebugging.h
=> Merge release to master and bump version to 4.2.0

src/NativeScript/inspector/GlobalObjectConsoleClient.cpp, src/NativeScript/inspector/GlobalObjectConsoleClient.h
Reopening #932's changes as a new PR as it was meant to go in release instead of master.
=> fix(debugger): console.dir not displayed correctly in Safari inspector

CHANGELOG.md
=> docs: Update Changelog for 4.1.1

CHANGELOG.md
=> Update Changelog for 4.1.0

src/NativeScript/inspector/GlobalObjectDebuggerAgent.mm
It's prototype is to accept a scriptId instead of a path and that's what
Chrome DevTools sends to the backend.
Refs #958
=> fix(live-edit): Fix setScriptSource function implementation

CHANGELOG.md, build/npm/inspector_package.json, build/npm/runtime_package.json, src/NativeScript/JSErrors.h, src/NativeScript/JSErrors.mm, src/NativeScript/TNSRuntime.h, src/NativeScript/TNSRuntime.mm
=> Merge release to master and bump version to 4.3.0

build/npm/inspector_package.json, build/npm/runtime_package.json
ios-runtime and inspector package versions were 4.3.0
ios-runtime and inspector package versions are 5.0.0
=> chore: bump version to 5.0.0

build/npm/inspector_package.json, build/npm/runtime_package.json
ios-runtime and inspector package versions were 5.0.0
ios-runtime and inspector package versions are 5.1.0
=> chore: bump version to 5.1.0

CMakeLists.txt, build/scripts/build-livesync-static-lib.sh, build/scripts/build-nativescript-framework.sh, build/scripts/build-testrunner-application.sh, build/scripts/common.sh, build/scripts/package-tns-ios.sh, build/scripts/run-tests.js, src/WebKit.cmake
The framework is built with optimization option `-O2` and symbols information is not stripped.
The framework is built with optimization option `-O3` and symbols information is stripped.
=> NativeScript.framework linking optimizations

build/npm/inspector_package.json, build/npm/runtime_package.json
ios-runtime and inspector package versions were 5.1.0
ios-runtime and inspector package versions are 5.2.0
=> chore: bump version to 5.2.0

build/scripts/build-step-metadata-generator.py, build/scripts/get_version.py, build/scripts/update-version.py, src/debugging/Inspector/scripts/generate.py, src/debugging/Inspector/scripts/generate_typescript_interfaces.py
Fix styling issues in Python scripts.
No behavior changes.
No behavior changes.
=> chore: styling in python scripts

src/NativeScript/GlobalObject.h, src/NativeScript/GlobalObject.mm, src/NativeScript/JSErrors.h, src/NativeScript/JSErrors.mm
=> feat: OnDiscardedError handler

src/debugging/TNSDebugging.h
Enabled by: https://github.com/NativeScript/nativescript-cli/pull/4279
Related to: https://github.com/NativeScript/ios-runtime/issues/1053
=> fix: ensure a valid listenSource on each AttachRequest

src/NativeScript/TNSRuntime.mm, tests/TestRunner/app/package.json
=> feat: setting JSC options from ios.jscflags in app/package.json

src/NativeScript/JSErrors.mm, src/NativeScript/ObjC/TNSExceptionHandler.h
=> fix: do not report __onUncaughtError twice

build/npm/inspector_package.json, build/npm/runtime_package.json
ios-runtime and inspector package versions are 5.2.0
ios-runtime and inspector package versions are 5.3.0
=> chore: bump version to 5.3.0

CHANGELOG.md
=> chore: Update CHANGELOG for v5.2.0

src/NativeScript/inspector/GlobalObjectConsoleClient.cpp
=> Use the same method for console.log and console.trace

src/NativeScript/inspector/GlobalObjectConsoleClient.cpp
Related to #1009
Fixes console.trace() not logging the stack trace.
=> feat: use printConsoleMessageWithArguments for logging messages

src/NativeScript/JSErrors.mm
=> chore: add info about a string hardcoded in the CLI

build/scripts/build-testrunner-application.sh, cmake/CreateNativeScriptApp.cmake, src/NativeScript/CMakeLists.txt, src/NativeScript/inspector/InspectorPageAgent.mm
This was no longer happening after merging the fix of #1021
=> fix(livesync): `__onLiveSync` function must be called on the UI thread

CHANGELOG.md, build/npm/inspector_package.json, build/npm/runtime_package.json
Patch release 5.3.1 is needed because #1108 was not released with 5.3.0 by mistake
=> chore: Bump version and update CHANGELOG for version 5.3.1

build/project-template/internal/main.m
Local headers should be added with quoted-style includes
Related to #1113
=> Fix: Change angled bracketed includes to quoted

build/project-template/internal/nsld.sh
Build fails on XCode 10.2.
Build succeeding.
=> fix: Update nsld.sh to use the #!/usr/bin/env bash shebang

build/npm/inspector_package.json, build/npm/runtime_package.json
ios-runtime and inspector package versions are 5.3.1
ios-runtime and inspector package versions are 6.0.0
=> chore: Bump version to 6.0.0

CHANGELOG.md
=> chore: Update CHANGELOG for v5.4.2

src/NativeScript/JSErrors.mm
=> refactor: improve stackTrace for readability

src/debugging/TNSDebugging.h
The application refresh is supported only with the `Page.reload` debug protocol message through the debug socket.
The application refresh is also supported by the iOS notifications service and you are not forced to start a debug session in order to refresh the application.
- The code is copied from the LiveSync plugin of the Preview app and we will also reuse this notification there.
- We need this feature in order to release the Wi-Fi iOS devices story with HMR support as we will not be able to connect to the debug socket of Wi-Fi devices in the initial version.
- The initial HMR update will be faster because we will not create debug socket connections.
- The users will not see the strange `NativeScript debugger attached` message during the first HMR update.
Related to: …
=> feat: support app refresh through the notifications service

src/debugging/TNSDebugging.h
=> fix: fix a memory leak

README.md, build/project-template/__PROJECT_NAME__.xcodeproj/project.pbxproj, src/NativeScript/Calling/FunctionWrapper.mm, tests/TestFixtures/Interfaces/TNSMethodCalls.h, tests/TestFixtures/Interfaces/TNSMethodCalls.m, tests/TestRunner/app/Inheritance/InheritanceTests.js
=> fix: don't call postInvocation if there's exception

README.md, build/npm/inspector_package.json, build/npm/runtime_package.json
* chore: Bump package versions to 6.1.1
* chore(metadata-generator): Fix tests
* chore: Update LLVM requirement
=> chore: Fix metadata generator tests

build/npm/inspector_package.json, src/debugging/Inspector/Inspector/NativeScript Inspector/InspectorFrontendHost.m, src/debugging/Inspector/Inspector/NativeScript Inspector/InspectorFrontendHostProtocol.h, src/debugging/debugger-proxy.js
=> fix(inspector): JS Error due to missing methods from InspectorFrontendHost

build/scripts/build-step-metadata-generator.py
pull request based on this issue: https://github.com/NativeScript/NativeScript/issues/9840 and this patch: https://github.com/NativeScript/ns-v8ios-runtime/commit/1e0c0cec0e9627cd72652208347e760809f7d1e1
=> build for iOS - KeyError: 'DEPLOYMENT_TARGET_CLANG_FLAG_NAME'

build/project-template/__PROJECT_NAME__.xcodeproj/project.pbxproj, build/project-template/internal/nativescript-pre-build
App using the JSC fails to compile using XCode14
Fixes app build with Xcode 14. 
Changes taken from https://github.com/NativeScript/ns-v8ios-runtime/commit/3b1eafc4da502404ab8c50854016ff059ae8eff8
=> fix: Xcode14 build
