src/NativeScript/NativeScript/GlobalObject.mm
Promise reactions and other microtasks are executed on the current RunLoop in its default mode. Move this execution to the set of common modes to bump its priority.
Fixes #39
=> Enqueue microtasks with the common runloop modes

gruntfile.js, src/NativeScript/NativeScript/GlobalObject.h, src/NativeScript/NativeScript/GlobalObject.mm
This commit speeds up the debugger and makes it usable.
Also fixes the crash on device.
=> Remove getOwnPropertyNames override of GlobalObject

build/project-template/__PROJECT_NAME__/main.m, examples/Gameraww/Gameraww/main.m, examples/TNSApp/TNSApp/main.m, src/NativeScript/NativeScript/JSErrors.mm, src/NativeScript/NativeScript/TNSRuntime+Inspector.h, src/NativeScript/NativeScript/TNSRuntime+Inspector.mm, src/NativeScript/NativeScript/TNSRuntime+Private.h, src/NativeScript/NativeScript/TNSRuntime.h, src/NativeScript/NativeScript/TNSRuntime.mm, tests/NativeScriptTests/NativeScriptTests/Utilities.h, tests/NativeScriptTests/NativeScriptTests/Utilities.m, tests/NativeScriptTests/NativeScriptTests/main.m
A general way to handle uncaught errors from the runtime. Expose the necessary APIs to let handlers spin up the inspector runloop.
=> Add a global uncaught error handler

src/debugging/WebInspectorUI-600.1.4/UserInterface/Protocol/InspectorFrontendHostStub.js
When a webserver on the device hosts the inspector,
the WebSocket client should connect to the device.
Currently it connects to "localhost" which is the Mac or PC from where it is accessed.
=> The hostname of the WebSocket server will be the same as the web host that servers the web inspector pages

src/NativeScript/NativeScript/FFICall.h, src/NativeScript/NativeScript/FFIFunctionCall.mm, src/NativeScript/NativeScript/ObjCBlockCall.mm, src/NativeScript/NativeScript/ObjCClassBuilder.mm, src/NativeScript/NativeScript/ObjCConstructorCall.mm, src/NativeScript/NativeScript/ObjCMethodCall.mm
Turns out there's a nasty race condition waiting to happen if a thread other than the one that owns the VM tries to call into JavaScript using `FFICallback`. The guilty party is `ABAddressBookRequestAccessWithCompletion`, whose completion block is called on an arbitrary queue. This queue tries to acquire the VM's API lock, but fails because the VM owner thread is still holding on to it.
The answer is to temporarily drop all locks before calling a native API so that a worker thread spawned by the native API can have the chance to acquire the API lock.
=> Drop all locks when calling out to native

src/debugging/TNSDebugging.h, src/debugging/debugger-proxy.js
Graphite uses UTF-16 and thus its easier to change it here rather than break Graphite as well.
=> Change TNSDebugging's transport encoding

src/NativeScript/GlobalObject.mm, src/NativeScript/Metadata/Metadata.h, src/NativeScript/ObjC/Constructor/ObjCConstructorNative.mm, src/NativeScript/ObjC/ObjCPrototype.mm, src/NativeScript/TypeFactory.mm
Each meta has a pointer to ModuleMeta structure which describes a top level module (only top level modules can be required). All ModuleMeta structures are also kept in global ModuleTable (an array of pointers to ModuleMetas, sorted by module name). This table is used to perform lookups by module name.
=> Insert richer modules information in metadata and expose it in metadata API.

src/NativeScript/ObjC/Constructor/ObjCConstructorCall.mm, tests/TestFixtures/CMakeLists.txt, tests/TestFixtures/Interfaces/TNSClassWithPlaceholder.h, tests/TestFixtures/Interfaces/TNSClassWithPlaceholder.m, tests/TestFixtures/TestFixtures.h, tests/TestRunner/app/ObjCConstructors.js, tests/TestRunner/app/bootstrap.js
`ObjCConstructorCall` used to release the object returned by `alloc`, but it has to release the object returned by the initializer call instead, to account for cases when `alloc` returns a dummy placeholder factory object or when an initializer replaces `self`.
=> Release the proper value when new-ing classes

build/scripts/build.sh, gruntfile.js
The project template will now strip the unwanted architectures.
=> Remove the release build of the shared framework.

src/NativeScript/require.js
This reduces the Cuteness load time from 730ms to 630ms on iPhone 5s in Release.
=> Cache require paths - close #139.

src/debugging/TNSDebugging.h
The JSStringCreateWithCFString symbol, used in TNSDebugging.h, seems to be stripped from the dynamic NativeScript.framework. Replaced it with JSStringCreateWithUTF8CString so that the debugging can work with that framework.
=> TNSDebugging should work with the dynamic NativeScript.framework.

build/scripts/metadata-generation-build-step.sh, tests/TestFixtures/Interfaces/TNSClassWithPlaceholder.m
To parse iOS 9 SDK headers, we strip on the fly all unfamiliar syntax.
=> Support for iOS 9 and new Objective-C syntax (generics, nullability specifiers, new keywords etc.)

src/NativeScript/CMakeLists.txt, src/NativeScript/GlobalObject.h, src/NativeScript/GlobalObject.mm, src/NativeScript/JSErrors.h, src/NativeScript/ObjC/Enumeration/ObjCFastEnumerationIterator.h, src/NativeScript/ObjC/Enumeration/ObjCFastEnumerationIterator.mm, src/NativeScript/ObjC/Enumeration/ObjCFastEnumerationIteratorPrototype.h, src/NativeScript/ObjC/Enumeration/ObjCFastEnumerationIteratorPrototype.mm, src/NativeScript/ObjC/Enumeration/TNSFastEnumerationAdapter.h, src/NativeScript/ObjC/Enumeration/TNSFastEnumerationAdapter.mm, src/NativeScript/ObjC/Inheritance/ObjCClassBuilder.mm, src/NativeScript/ObjC/ObjCPrototype.h, src/NativeScript/ObjC/ObjCPrototype.mm, src/NativeScript/ObjC/TNSArrayAdapter.mm, tests/TestFixtures/Interfaces/TNSInheritance.h, tests/TestFixtures/Interfaces/TNSInheritance.m, tests/TestRunner/app/ApiTests.js, tests/TestRunner/app/Inheritance/InheritanceTests.js, tests/TestRunner/app/Marshalling/ObjCTypesTests.js
This change exposes the Objective-C fast enumeration machinery by adding a `Symbol.iterator` property to the prototype of classes that implement fast enumeration.
This allows code expressed with a `for...in` statement in Objective-C to be implemented with JavaScript's `for...of` statement in NativeScript. Also, JavaScript APIs that expect iterable objects can now consume `NSFastEnumeration`-conforming Objective-C objects.
What's more, `TNSArrayAdapter` now implements bulk enumeration to speed up fast enumeration when the adapted object is the array exotic.
=> Implement and consume NSFastEnumeration

src/NativeScript/AllocatedPlaceholder.cpp, src/NativeScript/AllocatedPlaceholder.h, src/NativeScript/GlobalObject.h, src/NativeScript/GlobalObject.mm, src/NativeScript/ObjC/Constructor/ObjCConstructorBase.mm, src/NativeScript/ObjC/ObjCPrimitiveTypes.mm, src/NativeScript/ObjC/ObjCSuperObject.mm, src/NativeScript/ObjC/ObjCWrapperObject.mm
When the inspector is enabled and a breakpoint is hit a Runtime.getDisplayableProperties message is dispatched. The logic behind Runtime.getDisplayableProperties enumerates getOwnPropertyNames and getOwnPropertySymbols and calls their toString method.
This results in a JSValue::toString call that defaults to JSCell::defaultValue which is guarded by a RELEASE_ASSERT_NOT_REACHED().
As a workaround do not register the instance structure
=> Do not register the instance structure

src/NativeScript/ObjC/Inheritance/ObjCTypeScriptExtend.mm, tests/TestRunner/app/Inheritance/TypeScriptTests.js, tests/TestRunner/app/Inheritance/TypeScriptTests.ts
There are more places the original constructor function resides in various circumstances. We loop over all the frame registers AND the lexical environment of the scope chain to try and replace the constructor function with our own.
Fixes #249
=> Fix TypeScript inheritance of Objective-C classes

src/NativeScript/ObjC/Block/ObjCBlockCall.mm
WTF::RetainPtr calls CFRetain on the block which is the same thing, but it ignores the return value which is crucial for blocks.
=> Call Block_copy in ObjCBlockCall::finishCreation

build/project-template/__PROJECT_NAME__.xcodeproj/project.pbxproj
Remove hardcoding of icon fileset from the template .pbxproj file.
By doing so, we give more flexibility to the end user when they choose icons for their app.
=> Delete hardcoded .png references.

src/NativeScript/ObjC/Inheritance/ObjCClassBuilder.mm
When memory-managing an instance of a class derived from an Objective-C one there is that sliver of time after the JavaScript representation of the object has been garbage-collected, but the Objective-C representation is still alive. Calls to `retain` or `release` will try to access a JavaScript object that's not there anymore, so guard against that.
=> -[TNSValueWrapper value] can return null

src/NativeScript/GlobalObject.mm, src/NativeScript/ObjC/Constructor/ObjCConstructorNative.mm, src/NativeScript/ObjC/ObjCPrototype.mm, src/NativeScript/SymbolLoader.h, src/NativeScript/SymbolLoader.mm, src/NativeScript/TypeFactory.mm
Make SymbolLoader cache by the ModuleMeta pointer, which is unique.
SymbolLoader now supports embedded frameworks.
Stubbed support for dylibs.
Fixes #273
=> Overhaul SymbolLoader

src/MetadataGenerator.cmake
Otherwise it won't be able to run on an older OS X version than the one it was originally built on.
=> Explicitly set the metadata generator's OS X deployment target

src/NativeScript/require.js
Check if such file exists before falling back to directory
https://github.com/NativeScript/ios-runtime/issues/286
=> Require file when there is a directory with same name

src/NativeScript/inspector/CachedResource.mm, src/debugging/TNSDebugging.h
If we pause right away the debugger messages that are send are not handled because the frontend is not yet initialized
=> Delay debugger pausing

src/NativeScript/Marshalling/Record/RecordInstance.h, src/NativeScript/Marshalling/Reference/ReferenceConstructor.cpp, src/NativeScript/Marshalling/Reference/ReferenceInstance.h, tests/TestRunner/app/Marshalling/ReferenceTests.js
and allocate an internal buffer of the correct size.
=> ReferenceConstructor should accept a single type argument

.gitignore, src/debugging/Inspector/Inspector/Inspector.xcodeproj/project.pbxproj, src/debugging/Inspector/Inspector/Inspector/Info.plist, src/debugging/Inspector/Inspector/Inspector/main.m, src/debugging/Inspector/Inspector/NativeScript Inspector/Communication.m, src/debugging/Inspector/Inspector/NativeScript Inspector/InspectorFrontendHost.h, src/debugging/Inspector/Inspector/NativeScript Inspector/InspectorFrontendHost.m, src/debugging/Inspector/Inspector/NativeScript Inspector/InspectorFrontendHostProtocol.h, src/debugging/Inspector/Inspector/NativeScript Inspector/ViewController.h, src/debugging/Inspector/Inspector/NativeScript Inspector/ViewController.m, src/debugging/TNSDebugging.h, src/debugging/inspector/Inspector/NativeScript Inspector/Communication.h
=> Inject InspectorFrontendHost in the Inspector frontend and communicate over raw sockets

tests/TestRunner/app/Marshalling/ConstantsTests.js
Related issue: https://github.com/NativeScript/ios-runtime/issues/279
Merge after https://github.com/NativeScript/ios-metadata-generator/pull/23
Ready for merge.
=> Expose compile-time constants as JsCode

build/project-template/__PROJECT_NAME__.xcodeproj/project.pbxproj, build/project-template/__PROJECT_NAME__/build-debug.xcconfig, build/project-template/__PROJECT_NAME__/build-release.xcconfig, build/project-template/__PROJECT_NAME__/build.xcconfig
* Moved the build.xcconfig to target level
* When installing cocoapods, it will not remove it, so we include cocoapods xcconfigs
* A not found xcconfig is not a build error
This is done because there is a Pod target that doesn't need NativeScript xcconfig.
=> Fix cocoapods

src/NativeScript/inspector/SourceProviderManager.cpp
WTF::String::format() messes up with the utf8 characters. https://bugs.webkit.org/show_bug.cgi?id=37327
=> Fix mangling of utf8 characters in module code

tests/TestFixtures/Api/TNSReturnsRetained.h, tests/TestFixtures/Api/TNSReturnsRetained.m, tests/TestFixtures/CMakeLists.txt, tests/TestFixtures/TestFixtures.h, tests/TestFixtures/exported-symbols.txt, tests/TestRunner/app/ApiTests.js, tests/TestRunner/app/FunctionsTests.js
Issue #13.
List of changed functions: https://gist.github.com/jasssonpet/327862790a058523179c/ab13608349d6144d6be3741b1df0fcb12d26c947.
Merge after: https://github.com/NativeScript/ios-metadata-generator/pull/26 and https://github.com/NativeScript/ios-runtime/pull/358.
Related: https://github.com/NativeScript/NativeScript/pull/899 and https://github.com/NativeScript/ios-runtime-docs/pull/35.
=> Update returns retained logic and add tests

src/MetadataGenerator.cmake
Merge with: https://github.com/NativeScript/ios-metadata-generator/pull/28
=> Revert "Explicitly set the metadata generator's OS X deployment target"

build/scripts/build.sh, cmake/CreateNativeScriptApp.cmake, gruntfile.js, src/NativeScript/CMakeLists.txt
https://github.com/NativeScript/ios-runtime/issues/242
Requires Xcode 7 on build machines.
=> Generate dSYM for NativeScript.framework

build/project-template/internal/nativescript-post-build, build/project-template/internal/nativescript-pre-build, build/project-template/internal/nativescript-pre-link, build/scripts/metadata-generation-build-step
Make build steps to fail if an internal command fails. Print meaningful message when metadata generation step fails.
=> Make build steps to fail if an internal command fails

build/project-template/__PROJECT_NAME__.xcodeproj/project.pbxproj, build/project-template/__PROJECT_NAME__/__PROJECT_NAME__-Info.plist, build/project-template/__PROJECT_NAME__/en.lproj/LaunchScreen.xib
Reverts NativeScript/ios-runtime#390
<b>Description</b>: Restore `LaunchScreen.xib` and `UILaunchStoryboardName` plist key due to scalling issues. I will continue investigating the issue mentioned in https://github.com/NativeScript/ios-runtime/pull/390.
=> Revert "Remove LaunchScreen.xib from project."

src/NativeScript/CMakeLists.txt, src/NativeScript/GlobalObject.h, src/NativeScript/GlobalObject.mm, src/NativeScript/Marshalling/FFIType.cpp, src/NativeScript/Metadata/Metadata.h, src/NativeScript/ObjC/Unmanaged/UnmanagedInstance.cpp, src/NativeScript/ObjC/Unmanaged/UnmanagedInstance.h, src/NativeScript/ObjC/Unmanaged/UnmanagedPrototype.h, src/NativeScript/ObjC/Unmanaged/UnmanagedPrototype.mm, src/NativeScript/ObjC/Unmanaged/UnmanagedType.cpp, src/NativeScript/ObjC/Unmanaged/UnmanagedType.h, src/ts/Interop.d.ts, tests/TestFixtures/Api/TNSBridgedTypes.h, tests/TestFixtures/Api/TNSReturnsRetained.h, tests/TestFixtures/Api/TNSReturnsRetained.m, tests/TestFixtures/Api/TNSReturnsUnmanaged.h, tests/TestFixtures/Api/TNSReturnsUnmanaged.m, tests/TestFixtures/CMakeLists.txt, tests/TestFixtures/Marshalling/TNSObjCTypes.h, tests/TestFixtures/Marshalling/TNSObjCTypes.m, tests/TestFixtures/TestFixtures.h, tests/TestFixtures/exported-symbols.txt, tests/TestRunner/app/ApiTests.js
#13
https://github.com/NativeScript/ios-metadata-generator/pull/32
=> Return an Unmanaged Type when we don't know how to memory manage an item

src/debugging/TNSDebugging.h
This removes the annoying "Address already in use" errors when you start a debugging session shortly after one has finished.
=> Reuse debugging socket

src/NativeScript/TNSRuntime.mm
We are disabling JIT because of a bug found in the latest webkit version, causing some tests to fail. We can't figure out the actual piece of code causing the bug, but disabling JIT makes it disappear.
P.S. Til now, JIT was enabled only on simulator, because of iOS restrictions, so the change will not affect device builds.
=> Disable JIT

src/NativeScript/require.js
Here is how it looks now:
```
JavaScript stack trace:
1   __findModule@require.js:96:170
2   __loadModule@require.js:143:42
3   __require@require.js:118:32
4   anonymous@file:///app/test/test.js:3:8
5   __executeModule@require.js:129:27
6   __loadModule@require.js:157:24
7   __require@require.js:118:32
8   anonymous@file:///app/index.js:1:78
9   __executeModule@require.js:129:27
10  __loadModule@require.js:157:24
JavaScript error:
require.js:96:170: JS ERROR Error: Failed to find module '../no' relative to 'file:///app/test/test.js'. Computed path: 'app/no.js'.
```
By prepending all of our internal functions with `__`, it's easy for the user to find his functions in a glance.
As @PanayotCankov suggested, file paths are clickable in the Inspector now:
Close #407.
=> Simplify require errors.

src/NativeScript/inspector/GlobalObjectInspectorController.cpp, src/NativeScript/inspector/GlobalObjectInspectorController.h, src/debugging/Inspector/scripts/generate.py
Also expose inspectorTimestamp method that would be used from modules guys to record a timeline event. Doing that in JavaScript was not possible because the elapsed time is based on some context that is held and modified by several different places
=> Add all properties of domain types to the TypeScript generated glue code

src/NativeScript/Calling/FFICall.cpp, src/NativeScript/GlobalObject.h, src/NativeScript/Marshalling/Fundamentals/FFIPrimitiveTypes.cpp, src/NativeScript/ObjC/Inheritance/ObjCClassBuilder.h, src/NativeScript/ObjC/Inheritance/ObjCClassBuilder.mm, src/NativeScript/ObjC/ObjCMethodCall.mm, src/NativeScript/Runtime/ReleasePool.h
This yields a ~100% performance improvement in synthetic benchmarks.
=> Performance improvements for method calls

src/NativeScript/GlobalObject.h, src/NativeScript/GlobalObject.mm, src/NativeScript/Interop.h, src/NativeScript/ObjC/Constructor/ObjCConstructorBase.mm, src/NativeScript/ObjC/Enumeration/TNSFastEnumerationAdapter.h, src/NativeScript/ObjC/Enumeration/TNSFastEnumerationAdapter.mm, src/NativeScript/ObjC/Inheritance/ObjCClassBuilder.mm, src/NativeScript/ObjC/ObjCMethodCall.mm, src/NativeScript/ObjC/ObjCPrimitiveTypes.mm, src/NativeScript/ObjC/ObjCTypes.h, src/NativeScript/ObjC/ObjCTypes.mm, src/NativeScript/ObjC/ObjCWrapperObject.h, src/NativeScript/ObjC/ObjCWrapperObject.mm, src/NativeScript/ObjC/TNSArrayAdapter.mm, src/NativeScript/ObjC/TNSDataAdapter.mm, src/NativeScript/ObjC/TNSDictionaryAdapter.mm
This nets us a few small performance wins because we no longer use the thread-safe Objective-C association API to store JavaScript wrappers in native objects.
=> Replace ObjC association with WeakGCMap

src/NativeScript/__extends.js
Get the latest `__extends` function from TypeScript compiler. Allows to classes to extend from `null`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/extends#Extending_null.
=> Allow vanilla TypeScript classes to extend null

src/NativeScript/CMakeLists.txt, src/NativeScript/Interop.h, src/NativeScript/Interop.mm, src/NativeScript/ObjC/NSErrorWrapperConstructor.h, src/NativeScript/ObjC/NSErrorWrapperConstructor.mm, src/NativeScript/ObjC/ObjCMethodCall.mm, src/ts/Interop.d.ts, tests/TestRunner/app/ApiTests.js
Introduce the new `NSErrorWrapper` that will wrap an `NSError` thrown in JavaScript so that it can retain the `message` and `stack` properties expected in all JavaScript errors.
=> Wrap bridged NSError objects in JavaScript Errors

src/NativeScript/ObjC/TNSDictionaryAdapter.mm
Otherwise the "current thread is holding api lock" assert fails.
=> Lock in TNSDictionaryAdapter keyEnumerator

examples/Gameraww/app/MasterViewController.js, src/NativeScript/ObjC/Constructor/ObjCConstructorBase.mm, tests/TestRunner/app/ObjCConstructors.js
This patch augments the JavaScript constructability of Objective-C classes. Constructor functions for Objective-C classes now support initialization via the Swift-style named parameter syntax which mimics Swift's initializer syntax.
Examples:
`NSURL.alloc().initWithString(aString)` becomes `new NSURL({ string: aString })`
`NSURL.alloc().initFileURLWithPath(aString)` becomes `new NSURL({ fileURLWithPath: aString })`
`NSString.alloc().initWithContentsOfFileEncodingError(aString, anEncoding)` becomes `new NSString({ contentsOfFile: aString, encoding: anEncoding })`
=> Swift-style initializers

build/scripts/metadata-generation-build-step
First merge: https://github.com/NativeScript/ios-metadata-generator/pull/37
TypeScript declarations look like this:
Function:
```typescript
/**
* Creates and returns a new instance of a given class.
* @param aClass - The class of which to create an instance.
* @param extraBytes - The number of extra bytes required for indexed instance variables (this value is typically 0).
* @param zone - The zone in which to create the new instance (pass NULL to specify the default zone).
*/
declare function NSAllocateObject(aClass: typeof NSObject, extraBytes: number, zone: interop.Pointer): any;
```
Constant:
```typescript
/**
* All directories where resources can occur.
*/
declare const NSAllLibrariesDirectory: number;
```
Interface (with static method, instance method and property):
```typescript
/** …
```
=> Generate TypeScript comments in TypeScript declarations

src/debugging/TNSDebugging.h
Currently we have a delay of one second before we pause the application so that the inspector frontend would have enough time to initialize. We schedule the pause logic on the main loop and wake it up in order to execute it. We than call CFRunLoopStop which was supposed to stop the runloop that loops for 30 seconds waiting for an inspector frontend connection. Since the CFRunLoopStop is right after the 1 second pause it stops this pass of the runloop, not the 30 seconds one.  So to fix it we wait until isWaitingForDebugger becomes NO and isWaitingForDebugger is set to NO 30 seconds after the ReadyForAttach notification
=> Fix for debugger connecting after a delay

build/project-template/internal/main.m, build/scripts/build-runtime.sh, build/scripts/build.sh, cmake/CreateNativeScriptApp.cmake, cmake/main.m, examples/BlankApp/main.m, src/NativeScript/CMakeLists.txt, src/NativeScript/JSErrors.mm, src/NativeScript/NativeScript.h, src/NativeScript/ObjC/TNSExceptionHandler.h, src/NativeScript/TNSRuntime+Diagnostics.h, src/NativeScript/TNSRuntime+Diagnostics.mm, src/NativeScript/TNSRuntime.h, src/NativeScript/TNSRuntime.mm, src/debugging/TNSDebugging.h, tests/TestFixtures/exported-symbols.txt
Looking forward to some comments.
New output includes JS stack trace. Example with https://github.com/NativeScript/NativeScript/issues/1426:
```
2016-02-03 17:58:13.382 HelloWorldApp[81228:1483108] *** JavaScript call stack:
(
0   _updateIOSTabBarColorsAndFonts@file:///app/tns_modules/ui/tab-view/tab-view.js:282:30
1   setFontInternalProperty@file:///app/tns_modules/ui/styling/stylers.js:698:43
2   applyProperty@file:///app/tns_modules/ui/styling/stylers-common.js:27:28
3   _applyStyleProperty@file:///app/tns_modules/ui/styling/style.js:715:42
4   @file:///app/tns_modules/ui/styling/style.js:636:103
5   forEach@[native code]
6   _endUpdate@file:///app/tns_modules/ui/styling/style.js:636:40
7   applySelectors@file:///app/tns_modules/ui/styling/style-scope.js:127:30
8 …
```
=> TNS Objective-C exception handler

src/NativeScript/GlobalObject.mm, src/NativeScript/ObjC/ObjCMethodCall.mm, src/NativeScript/ObjC/ObjCProtocolWrapper.h, src/NativeScript/ObjC/ObjCProtocolWrapper.mm, src/NativeScript/ObjC/ObjCPrototype.h, src/NativeScript/ObjC/ObjCPrototype.mm, tests/TestRunner/app/ApiTests.js, tests/TestRunner/app/Marshalling/ProtocolTests.js, tests/TestRunner/app/index.js
The following methods and properties are now available to all Objective-C protocol wrappers:
```javascript
var staticMethod = TNSBaseProtocol1.baseProtocolMethod1;
var instanceMethod = TNSBaseProtocol1.prototype.baseProtocolMethod1;
var instanceProperty = Object.getOwnPropertyDescriptor(TNSBaseProtocol1.prototype, 'baseProtocolProperty1');
```
This allows methods like https://github.com/NativeScript/NativeScript/pull/1531/files to be called in the following way:
```javascript
UIViewControllerContextTransitioning.prototype.containerView.call(transitionContext);
```
Close https://github.com/NativeScript/ios-runtime/issues/466
=> Add methods to Objective-C protocol wrappers

src/NativeScript/CMakeLists.txt, src/NativeScript/GlobalObject.h, src/NativeScript/TNSRuntime+Inspector.mm, src/NativeScript/inspector/DomainBackendDispatcher.cpp, src/NativeScript/inspector/SuppressAllPauses.cpp, src/NativeScript/inspector/SuppressAllPauses.h
In order to have source maps we needed a way to execute some java script that would return the source map content before the first application line. The end user should not see this so we hide it from the debugger. If you want to debug it you should pass a ТNS_dontSuppressAllPauses environment variable
=> Provide a way to execute inspector logic that should run before the first line of the application

src/NativeScript/ObjC/Constructor/ObjCConstructorBase.h, src/NativeScript/ObjC/Constructor/ObjCConstructorBase.mm, src/NativeScript/ObjC/Constructor/ObjCConstructorDerived.cpp, src/NativeScript/ObjC/Constructor/ObjCConstructorDerived.h, src/NativeScript/ObjC/Constructor/ObjCConstructorNative.h, src/NativeScript/ObjC/Constructor/ObjCConstructorNative.mm, src/NativeScript/ObjC/Inheritance/ObjCClassBuilder.mm, src/NativeScript/ObjC/ObjCPrototype.h, src/NativeScript/TypeFactory.mm
1. Unify initializers generation logic in `ObjCConstructorNative` and `ObjCConstructorDerived`. Conceptually, it is the same, so there is no reason to be in two places.
2. `ObjCConstructor`s don't need `InterfaceMeta` to be initialized. They already require a prototype from where they can get the `InterfaceMeta`.
3. `ObjCConstructorDerived` don't need a parent constructor to be initialized, anymore.
Also, this makes `ObjCConstructorDerived` class almost identical to its base class (`ObjCConstructorBase`). This will allow us to remove it in the future.
=> Unify initializers generation logic in ObjCConstructorBase

src/NativeScript/ObjC/Inheritance/ObjCClassBuilder.mm
Throw error when overriding a (non-readonly) native property without both a getter/setter function:
```objective-c
@interface TNSBaseInterface : NSObject
@property int baseProperty;
@end
```
```javascript
TNSBaseInterface.extend({
get baseProperty() {
console.log('get');
return this.super.baseProperty;
},
// set baseProperty(value) {
//     console.log('set');
//     this.super.baseProperty = value;
// },
});
```
=> Throw error when overriding properties without getter/setter.

src/NativeScript/CMakeLists.txt, src/NativeScript/inspector/CachedResource.h, src/NativeScript/inspector/CachedResource.mm, src/NativeScript/inspector/GlobalObjectInspectorController.cpp, src/NativeScript/inspector/InspectorNetworkAgent.cpp, src/NativeScript/inspector/InspectorNetworkAgent.h, src/NativeScript/inspector/InspectorPageAgent.h, src/NativeScript/inspector/InspectorPageAgent.mm
This is necessary for the scenarios where somebody wants to use the runtime without the modules. This agent will be overridden when the modules provide custom network domain implementation
=> Provide runtime implementation for source maps

src/NativeScript/Metadata/Metadata.h, src/NativeScript/Metadata/Metadata.mm, src/NativeScript/ObjC/Constructor/ObjCConstructorBase.mm
First this must be merged: https://github.com/NativeScript/ios-metadata-generator/pull/51
Fixes: https://github.com/NativeScript/ios-runtime/issues/504
=> Resolve swift-style initializers by searching in metadata instead of guessing the initializer name.

tests/TestFixtures/Api/TNSApi.h, tests/TestFixtures/Api/TNSApi.m, tests/TestFixtures/TNSTestNativeCallbacks.h, tests/TestFixtures/TNSTestNativeCallbacks.m, tests/TestRunner/app/Inheritance/InheritanceTests.js
When we see a method from a base class with the same name as a property in a derived class, we change the method metadata in the base class to property metadata, so tests that assert this behavior are added.
=> Name conflict tests

build/project-template/__PROJECT_NAME__/build-debug.xcconfig, build/project-template/__PROJECT_NAME__/build-release.xcconfig
The CLI already takes care to include these files' contents inside `plugins-debug` and `plugins-release` xcconfig files, so these includes are gratuitous. Moreover due to an [issue with CocoaPods 1.0.0](https://github.com/NativeScript/nativescript-cli/issues/1611), the referenced CocoaPods .xcconfig file path is wrong.
Ping @jasssonpet @KristinaKoeva
=> Remove CocoaPods .xcconfig file #includes

README.md
Fixes: https://github.com/NativeScript/ios-runtime/issues/546
The PR will be merged after all build machines are updated to llvm 3.8. 
To update to llvm 3.8:
1. Download the [pre-build binary of Clang for Mac OS X](http://www.llvm.org/releases/download.html#3.8.0).
2. Extract the content of the package (`/usr/local/lib` is a good candidate for a destination folder)
3. Include the path to `{llvm-root}/bin/llvm-config` or symlink to it in your `PATH`
4. Reset the cmake cache of the metadata generator project. This way the generator will be linked with the new version of Clang/LLVM.
=> Update metadata generator to use LLVM 3.8

tests/TestRunner/app/ApiTests.js
Related to: https://github.com/NativeScript/webkit/pull/4
=> Mock the usage of unorm_normalize in Webkit without modifing StringPrototype.cpp

src/NativeScript/GlobalObject.h, src/NativeScript/GlobalObject.mm, src/NativeScript/TNSRuntime.mm
Typical iOS application is always in an entry scope, because the UIApplicationMain method never finishes. On debugger attach the debugger agent tries to recreate the bytecode so that it could insert all opt debug codes. Since the vm is in an entry scope the recreation never happens. So to workaround this problem we execute all listeners when the run loop is idle and if the current entry scope is the UIApplicationMain
Fixes #315
=> Fix debugging for code that was already executed

src/NativeScript/GlobalObject.h
This option enables the profile_will_call and profile_did_call op codes that logs javascript method calls into the legacy profiler
Fixes #550
=> Add javascript method calls to profiler

src/NativeScript/inspector/CachedResource.mm
The app is initialized with the special live sync path that contains a space so URLWithString returns nil.
Fixes #572
=> Attaching a debugger crashes the app if it was already livesynced

src/NativeScript/inspector/DomainInspectorAgent.cpp, src/NativeScript/inspector/DomainInspectorAgent.h
willDestroyFrontendAndBackend is called when the debugger detaches from the application. m_constructorFunction is needed for every subsequent debugger session so clear it when the GlobalObjectInspectorController is released
Fixes #575
=> Fix subsequent debugger sessions crash the app

build/scripts/metadata-generation-build-step
=> Open stdout and stderr as text files regardless of python version

build/project-template/internal/strip-dynamic-framework-architectures.sh
It seems that in Xcode beta 4 it is required to sign the application and frameworks when building for iOS simulator platform. Otherwise the app crashes at runtime.
Xcode 7.3 settings:
```shell
$ xcodebuild -sdk "iphoneos" -showBuildSettings | grep "CODE_SIGN"
CODE_SIGNING_ALLOWED = YES
CODE_SIGNING_REQUIRED = YES
CODE_SIGN_IDENTITY = iPhone Developer
$ xcodebuild -sdk "iphonesimulator" -showBuildSettings | grep "CODE_SIGN"
CODE_SIGNING_ALLOWED = NO
```
Xcode 8 - beta 4 settings:
```shell
$ xcodebuild -sdk "iphoneos" -showBuildSettings | grep "CODE_SIGN"
CODE_SIGNING_ALLOWED = YES
CODE_SIGNING_REQUIRED = YES
CODE_SIGN_IDENTITY = iPhone Developer
$ xcodebuild -sdk "iphonesimulator" -showBuildSettings | grep "CODE_SIGN"
CODE_SIGNING_ALLOWED = YES
CODE_SIGN_IDENTITY = -
```
=> Sign frameworks for iOS simulator

src/NativeScript/Calling/FFICall.h, src/NativeScript/ObjC/ObjCMethodCall.mm, tests/TestFixtures/Marshalling/TNSRecords.h, tests/TestFixtures/TNSTestNativeCallbacks.h, tests/TestFixtures/TNSTestNativeCallbacks.m, tests/TestRunner/app/Marshalling/RecordTests.js
Tested on all 4 architectures. The tests should catch regressions.
Close #622
=> Fix struct marshalling by using libffi calculations

CHANGELOG.md, build/npm/inspector_package.json, build/npm/runtime_package.json, src/NativeScript/Calling/FFICall.h, src/NativeScript/ObjC/ObjCMethodCall.mm, tests/TestFixtures/Marshalling/TNSRecords.h, tests/TestFixtures/TNSTestNativeCallbacks.h, tests/TestFixtures/TNSTestNativeCallbacks.m, tests/TestRunner/app/Marshalling/RecordTests.js
Fixes https://github.com/NativeScript/ios-runtime/issues/622
Note that x86 and armv7 marshalling is changed only in master.
ping @dtopuzov, @vchimev
=> Prepare 2.2.1 release

src/NativeScript/CMakeLists.txt
This removes the 15 second "Generating dSYM" step.
This setting is also used for our internal apps (https://github.com/NativeScript/ios-runtime/blob/3fb755b74285c6afa06f0fa99b14fe603561ff69/cmake/CreateNativeScriptApp.cmake#L35) and is the default setting of the debug  configuration of newly created shared frameworks in Xcode.
=> Use DWARF only debug format for development builds of the NativeScript framework

src/libffi.cmake
This allows debugging libffi source:
https://github.com/NativeScript/ios-runtime/blob/da8f70c76170e38fe300327a9a6831665cc469e1/build/scripts/build-libffi.sh#L39-L41
=> Generate debug symbols for the libffi target by default

src/debugging/Inspector/Inspector/NativeScript Inspector/InspectorFrontendHost.m
=> Fix memory leak when passing Inspector messages

src/NativeScript/inspector/CachedResource.h, src/NativeScript/inspector/CachedResource.mm
The NSDirectoryEnumerator does not enumerate symbolic links, so when we have a symbolic link call the same method with the original file location
#626
=> Handle the case when we have tns_modules as symbolic link

src/NativeScript/Metadata/Metadata.h, src/NativeScript/Metadata/Metadata.mm, src/NativeScript/ObjC/Constructor/ObjCConstructorBase.h, src/NativeScript/ObjC/Constructor/ObjCConstructorNative.h, src/NativeScript/ObjC/Constructor/ObjCConstructorNative.mm, src/NativeScript/ObjC/Inheritance/ObjCClassBuilder.mm, src/NativeScript/ObjC/ObjCPrototype.mm, src/NativeScript/TypeFactory.mm
Same as https://github.com/NativeScript/ios-runtime/pull/612 but removes the tests so that the runtime can be built with Xcode 7 for the 2.3 release.
Requires Clang 3.9.
=> Class properties - Xcode 7

build/scripts/build-step-metadata-generator.py
Handle [change in the behavior of `map()` function](https://docs.python.org/3.0/whatsnew/3.0.html#views-and-iterators-instead-of-lists) in Python 3.
=> Makes the metadata generation build step compatible with Python 3

build/scripts/build-testrunner-application.sh
Reuse the release config runtime cache to speed up the builds.
This will remove all asserts that are enabled in debug config only from the runtime and it's dependencies (metadata generator, WebKit, libffi).
=> Build test app in release config

src/NativeScript/Calling/FFICall.cpp
Sometimes in Release builds the code block gets some random values which causes unexpected crashes. So initialize the code block with a default value.
=> Initialize the code block when fakeExecState is created

src/NativeScript/inspector/GlobalObjectDebuggerAgent.mm
Chrome dev tools don't have such option, so enable it by default
=> Enable breakpoints by default

src/NativeScript/inspector/DomainBackendDispatcher.cpp, src/NativeScript/inspector/DomainBackendDispatcher.h
Chrome dev tools calls Runtime.compile method which does not exist on the current webkit Runtime agent. So instead of moving the Runtime agent to our side, enable having one native and one javascript implementation
Merge with: https://github.com/NativeScript/webkit/pull/15
=> Call original domain dispatcher methods when there is no custom implementation

src/NativeScript/ObjC/Inheritance/ObjCTypeScriptExtend.mm
TypeScript 2.1 generates a constructor of the following type:
```javascript
return _super.apply(this, arguments) || this;
```
=> Update TypeScript extends empty constructor regex

src/NativeScript/inspector/GlobalObjectInspectorController.cpp, src/NativeScript/inspector/GlobalObjectInspectorController.h
Additionally, there are other places where the `ConsoleAgent` is used directly or the `ConsoleClient` is not reporting to the `LogAgent` and these will be addressed in the master branch for the next release.
=> GlobalObjectInspectorController::reportAPIException logs to DevTools Log agent

src/NativeScript/inspector/GlobalObjectDebuggerAgent.mm
These assertions fail when evaluating in the console when not on a breakpoint.
Assert that `executionContextId` is unused when debugging with Web Inspector and is equal to 1 when debugging with Chrome DevTools.
https://github.com/NativeScript/NativeScript/blob/0bb51e60653a865921f12a70c60c6671582a99a5/tns-core-modules/debugger/webinspector.ios.ts#L255
Merge with: https://github.com/NativeScript/webkit/pull/17
=> Change executionContextId assert to know of Chrome DevTools

src/debugging/Inspector/Inspector/NativeScript Inspector/InspectorFrontendHost.h, src/debugging/Inspector/Inspector/NativeScript Inspector/InspectorFrontendHost.m, src/debugging/Inspector/Inspector/NativeScript Inspector/InspectorFrontendHostProtocol.h
Fixes - https://github.com/NativeScript/ios-runtime/issues/685
=> Tabs are not supported in App Inspector so add an empty implementation for the openInNewTab method

build/project-template/__PROJECT_NAME__.xcodeproj/project.pbxproj
Add the AppIcon setting in the default template of the pbxproject. It appears it's not picked up correctly from the build.xcconfig as it was until now.
=> Fix the AppIcon setting

plugins/TKLiveSync/TKLiveSync/TKLiveSync.m, src/NativeScript/GlobalObject.moduleLoader.mm
`stringByStandardizingPath` will follow symlinks if the path contains `.` or `..`. The livesync copies just the app folder from the client application in a special folder and then symlinks the tns_modules in app as performance optimisation (syncing the tns_modules is slow when running with large amount of files). From that point on require with relative path within tns_modules will resolve to a path in the app bundle instead the sync folder. This has been fixed by manually normalizing paths containing `.` or `..`.
=> Fix livesync was not recreating the tns_modules simlink when launched from Xcode. Fix livesync making application module executed twice.

build/npm/runtime_package.json
ping @rosen-vladimirov @Mitko-Kerezov 
We need to allow this as a part of the LiveSync functionality for Fusion UI. 
We will not change the behavior for end users in the {N} CLI. Still will be throwing errors on not MAC OS machines, but will be able to LiveSync iOS project on Windows.
=> Allow iOS runtime to be installed not only on MAC OS

src/NativeScript/GlobalObject.moduleLoader.mm, tests/TestRunner/app/tns_modules/dummy-package/index.js, tests/TestRunner/app/tns_modules/dummy-package/package.json
A package placed in local `node_modules` folder will be required even if a package with the same name exists in `app/tns_modules` folder. This may affect the module loading performance.
Fixes: https://github.com/NativeScript/ios-runtime/issues/762
=> Fix module resolution logic

src/NativeScript/GlobalObject.mm, tests/TestRunner/app/RuntimeImplementedAPIs.js, tests/TestRunner/app/index.js
Calling
```
var n = __time();
``` 
Will get the current time in milliseconds but it is accuracy goes beyond millis. About 3 digit micro secs. are stored as fraction. Date.now() truncates to milis and is about 6 times slower.
=> Add a high resolution __time on the global object

src/NativeScript/GlobalObject.moduleLoader.mm
Related to: https://github.com/NativeScript/NativeScript/issues/4700, https://github.com/NativeScript/NativeScript/issues/4490
This PR fixes leak of `NSArray` and `NSString` objects in the base NativeScript project for iOS.
Since the iOS Runtime is built without ARC, we have to manage the lifecycle of the Objective-C objects manually. It seems we have forgotten to release some allocated Objective-C objects.
=> Fix memory leak

src/MetadataGenerator.cmake, src/WebKit.cmake
They manage their dependencies correctly and do not rebuild anything when no changes are made.
With the current scheme these are being built only once after the project is generated and
never again until the timestamps files are removed. If you change anything or have another reason
to rebuild, you have to manually delete the timestamps.
=> Always invoke build script for WebKit and MetadataGenerator targets

src/MetadataGenerator.cmake, src/WebKit.cmake
This reverts commit c53b972763f77ab315dae137f9fc045d9e4e8280.
When JSC project is being always rebuilt some symbols are
missing from the .a file for some reason
We're temporarily disabling this setting until we manage to fix the WK build.
=> Revert "Always invoke build script for WebKit and MetadataGenerator targets"

CONTRIBUTING.md, src/debugging/README.md, src/debugging/launch-proxy.sh, src/debugging/package.json, tools/pre-commit-clang-format
* Add `launch-proxy.sh` which npm installs and lauches the proxy in a `while true` block
* Add package.json for dependencies of proxy
* Add instructions for debugging from Xcode to README.md
=> Debugging from Xcode documentation and improvements

build/project-template/internal/main.m, src/NativeScript/TNSRuntime+Inspector.mm
Loading them asynchronously on inspector client connection can sporadically break
application startup due to the common dependencies between the application and
inspector modules.
=> Load inspector pages modules deterministically before launching app's main module

build/project-template/internal/main.m, src/NativeScript/TNSRuntime+Inspector.mm
This reverts commit 75f3317c1431926e9a57b48455359af23f4b092d.
This naive fix actually breaks debugging! The inspector modules must be executed after
the frontend client has connected because the domain handlers registration happens
through calling the `__inspectorSendEvent` function which sends a JSON message to the
frontend inspector socket.
=> Revert "Load inspector pages modules deterministically before launching app's main module"

src/MetadataGenerator.cmake, src/WebKit.cmake
The ${LLIntOutput} file is architecture-specific but resides in a common place. When we build for Simulator, it is created for the x86/x86_64 processor architectures. Afterwards all device builds will start failing because they need arm7/arm64 architectures but the file will be considered up-to-date and won't be regenerated. As a workaround we're creating an additional dependency of a stamp file per architecture. Whenever a specific architecture is generated, all other ones will be invalidated by touching the corresponding dependency files.
=> Make LLIntAssembly.h get regenerated after changing architecture target

src/NativeScript/TNSRuntime.mm
Bug https://github.com/NativeScript/NativeScript/issues/5019 describes a scenario when WTF may need to dispatch a method on the main thread. It needs a reference to the main run loop which however is never created. With calling `WTF::initializeMainThread()` we make sure all necessary references for the dispatch are created.
=> Initialize WTF main thread in TNSRuntime constructor

src/NativeScript/GlobalObject.moduleLoader.mm, src/NativeScript/JSErrors.mm, src/NativeScript/TNSRuntime.mm
=> When an error is thrown in a chained native promise the printed stack is insufficient

src/debugging/Inspector/Inspector/NativeScript Inspector/Communication.m
`connect` is asynchronous and can sometimes return `EINPROGRESS` error code which must be
handled by calling `select` to complete the connection operation.
=> Handle EINPROGRESS when connecting to backend socket

src/NativeScript/GlobalObject.moduleLoader.mm
This PR addresses an issue with absolute module paths not being resolved correctly in certain cases. For example, paths like ./A/moment.js and ../moment.js  did not resolve to the same path and the `moment.js` module was loaded twice like a different module.
See issue #822 for more details.
=> Fixes issues with resolution of canonical paths 

build/scripts/package-tns-ios.sh
`npm pack package` now treats `package` as a npm published package
instead of a local directory name. Disambiguate by changing it to `./package`
=> chore: Fix build with NPM 5

src/debugging/Inspector/Inspector/Inspector/main.m
There are internal APIs used by our WebKit build that are not present on High Sierra. We need to use the builtin WebCore frameworks to avoid crashing instead of our own. This fix checks if we are on High Sierra and resorts to the builtin frameworks if yes. We need this up until we upgrade to the latest WebKit version which does not use the internal APIs.
=> fix(inspector): Fix API compatibility issue with Inspector

src/NativeScript/TNSRuntime.mm
The app crashed whenever the debugger inspector tried to inspect the value of this property,
because `Exception` class' `Structure` has a `null` `globalObject` assigned. In order to prevent
inspection of the `__nsException` property we make its key a `Symbol`, because according to
[`Object.getOwnPropertyNames` documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames):
> The **Object.getOwnPropertyNames()** method returns an array of all properties (including
> non-enumerable properties **except for those which use Symbol**) found directly upon a given object.
The issue has been introduced with https://github.com/NativeScript/ios-runtime/pull/815
=> fix(JSC): Make __nsException property's key a Symbol

src/NativeScript/inspector/GlobalObjectConsoleClient.cpp
This PR addresses an issue with console.time() messages missing on iOS unless the Inspector console is used. The fix consists of extending the `InspectorConsoleAgent`'s API to return the generated console.time() message which is then consumed by the `GlobalObjectConsoleClient` which prints it in the Console.
Related: https://github.com/NativeScript/ios-runtime/issues/843
=> fix(console): Fix issue with missing console.time() messages.

src/NativeScript/Calling/FFICall.cpp, src/NativeScript/Calling/FFICallbackInlines.h, src/NativeScript/GlobalObject.mm, src/NativeScript/ObjC/Enumeration/TNSFastEnumerationAdapter.mm, src/NativeScript/ObjC/Inheritance/ObjCTypeScriptExtend.mm, src/NativeScript/ObjC/TNSDataAdapter.mm, src/NativeScript/TNSRuntime+Inspector.h, src/NativeScript/TNSRuntime+Inspector.mm, src/NativeScript/inspector/DomainBackendDispatcher.cpp, src/NativeScript/inspector/DomainInspectorAgent.cpp, src/NativeScript/inspector/InspectorLogAgent.cpp, src/NativeScript/inspector/InspectorNetworkAgent.cpp, src/NativeScript/inspector/InspectorPageAgent.mm, src/NativeScript/inspector/InspectorTimelineAgent.cpp, src/debugging/TNSDebugging.h
We identified a couple of issues with the way connections are handled between the Inspector and the backend. On one side, the sockets were not handled correctly using the Dispatch API resulting in faulty connections upon subsequent connection attempts. 
On the other side, there was an issue with the way Backend Dispatchers were handled via RefPtrs. For example, the DomainBackendDispatcher adopts a pointer to the dispatcher created by the DomainInspectorAgent, which also has a pointer to it. Adopting this pointer does not increase the refcount which in turn breaks the underlying object's (RefCountedBase) state.
The third amendment is in the way backend dispatchers are handled by the Agents in the `didCreateFrontendAndBackend` and `willDestroyFrontendAndBackend` calls. We now create a …
=> fix(inspector):  Fix app crashes on second debugger attach

src/debugging/TNSDebugging.h
It seems that we've regressed the functioning of `--debug-brk` by invoking `[inspector pause]` directly in the connection handling method. Revert to the old behaviour of executing 1 sec. of the main loop before calling it.
We'll further debug and try to understand whether this is the most appropriate fix for the issue, but for the 3.4.1 hotfix will keep the old behaviour.
=> fix(Inspector): CLI's --debug-brk option no longer works

src/debugging/Inspector/Inspector/Inspector/main.m
The
```
NSDictionary* configuration = @{
-            NSWorkspaceLaunchConfigurationArguments : @[ main_file_path, project_name, socket_path ]
-        };
```
literal creates a single-entry dictionary which throws an exception at a later point when `setValue` is called with additional key-value pairs.
=> fix(inspector): Fix issue with configuration dictionary.

build/npm/inspector_package.json
Due to problems in build scripts we erroneously published v3.4.1 in npm. Bump the version to 3.4.2
=> Bump inspector package version

build/npm/inspector_package.json
As per the latest discussions, we need to check the MACOSX version the Inspector is being installed on to unzip the corresponding binaries accordingly. This PR updates the postinstall script of the Inspector .tgz to generate a number representing the version of the OS (1012, 1013), checks if the version is 1013 or greater and chooses the HighSierra version of the Inspector. Otherwise the Sierra version is used.
Some questions:
* Do we want to restrict to Sierra and HighSierra only?
* Do we want to delete the .zip archives?
* How do we proceed in case the client updates the OS?
=> Update postinstall to check OS version.

src/debugging/Inspector/Inspector/Inspector/main.m
As discussed, in the updated version of WebKit we do not need to check the OS version when running the Inspector and pick against which WebKit libraries to link. We always use our own libraries as they are compatible with both Sierra and High Sierra. We just need to build them with different deployment targets.
=> Remove OS check for Font API usage in updated Inspector

tests/TestRunner/app/FunctionsTests.js
After upgrading WebKit to v11.0 we've encountered several issues with using private APIs forbidden for usage by apps on the AppStore. This PR addresses these issues in the following way:
- mock the unorm2_ APIs and replace them with our own `String.prototype.normalize` implementation using the official CFString APIs. This is done in `GlobalObject.mm` whereas the mocking is done in the WebKit's source code
- replace the usage of the private Crypto APIs with public APIs
A unit test is added that verifies the behavior of `String.prototype.normalize` against the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize specification.
=> Fix issues with using private Apple APIs

src/NativeScript/CMakeLists.txt, src/NativeScript/GlobalObject.h, src/NativeScript/GlobalObject.mm, src/NativeScript/inlineFunctions.js, src/NativeScript/inspector/GlobalObjectConsoleClient.cpp, src/NativeScript/inspector/GlobalObjectConsoleClient.h, src/NativeScript/smartStringify.js
This PR addresses issues with calling `console.dir` on objects in an iOS app. There are two aspects here:
- improve CLI filtering to pass multiline `console.log/console.dir` messages - https://github.com/NativeScript/nativescript-cli/pull/3389
- align `console.dir` behavior with android runtime's by introducing the `smartStringifyFunction` to handle circular references adequately.
Related issue: https://github.com/NativeScript/ios-runtime/issues/875
P.S.
There are functional tests covering this functionality.
=> fix(console-dir): Fix missing console.dir output

src/NativeScript/GlobalObject.mm, src/NativeScript/Interop.mm, src/NativeScript/Marshalling/Reference/ExtVectorTypeInstance.cpp, src/NativeScript/Marshalling/Reference/ExtVectorTypeInstance.h, src/NativeScript/Marshalling/Reference/IndexedRefTypeInstance.cpp, src/NativeScript/Marshalling/Reference/IndexedRefTypeInstance.h, src/NativeScript/ObjC/Constructor/ObjCConstructorCall.mm, src/NativeScript/ObjC/Inheritance/ObjCClassBuilder.mm, src/NativeScript/ObjC/ObjCMethodCall.mm, src/NativeScript/ObjC/ObjCMethodCallback.mm, src/NativeScript/TypeFactory.h, src/NativeScript/TypeFactory.mm
When arrays are passed as parameters in functions or returned by them, they are passed by reference so they should be parsed as ReferenceTypeInstance. When they are elements of other arrays/vectors or struct fields they are passed by value. In such cases they should be parsed as IndexedRefTypeInstance.
=> fix: Incorrect constant array type parsing

build/npm/inspector_package.json
In some cases, when CLI tries to install the `tns-ios-inspector` an error is thrown - `stderr maxbuffer exceeded`. This is caused by the huge output of the unzip operation executed on post install of the inspector. In order to fix this, pass `-q` (quiet) to the unzip operation.
The easiest way to reproduce the issue is to follow the steps below:
1. `tns create myApp`
2. `cd myApp`
3. `npm i --save-dev --ignore-scripts tns-ios-inpsector@rc`
4. `rm -rf node_modules`
5. `tns platform add ios@rc`
The last operation will fail.
The unzip operation is much quieter and the buffer is not exceeded.
=> fix(inspector): stderr maxbuffer exceeded is thrown during unzip

README.md, cmake-gen.sh
The recommended way of generating the iOS Runtime's Xcode project was to build NativeScript as a static library.
Create a script to generate the project with dynamic libraries. It works around the bug that CMake has when generating references to frameworks (for details see [this email thread](https://cmake.org/pipermail/cmake/2015-April/060484.html)).
=> chore(build): Create CMake project generation script

src/NativeScript/inspector/GlobalObjectConsoleClient.cpp, src/NativeScript/inspector/GlobalObjectConsoleClient.h
In Chrome DevTools console console.dir() prints only [object Object].
console.dir() prints objects properly formatted.
Fixes #906 .
=> fix: Format console message before sending it to the console client

cmake/ExportOptions.plist
Currently TestRunner application can not be exported after archiving on Xcode9 because of missing provisioning profile. This leads to failures in CI when try to build ios-runtime on machines with Xcode9
```
Step failed: <IDEDistributionSigningAssetsStep: 0x7fa60b183b30>: Error Domain=IDEDistributionSigningAssetStepErrorDomain Code=0 "Locating signing assets failed." UserInfo={NSLocalizedDescription=Locating signing assets failed., IDEDistributionSigningAssetStepUnderlyingErrors=(
13:54:25     "Error Domain=IDEProvisioningErrorDomain Code=9 \"\"TestRunner.app\" requires a provisioning profile.\" UserInfo={NSLocalizedDescription=\"TestRunner.app\" requires a provisioning profile., NSLocalizedRecoverySuggestion=Add a profile to the \"provisioningProfiles\" dictionary in your Export Options …
```
=> fix: update TestRunner app ExportOptions.plist

src/debugging/Inspector/Inspector/NativeScript Inspector/Communication.m, src/debugging/TNSDebugging.h, src/debugging/debugger-proxy.js
The inspector listening socket is being closed 30 sec. after the last
activity on it (opening, disconnection, etc). It had to be closed in order 
to have the hardcoded port number 18181 available for other apps after
finishing (or never starting) a debugging session. Without this timeout 
the first app that opened the port would take it for as long as it's running 
and would prevent any subsequent debugging attempts of another app on
the same iOS device; or even any {N} app on any iOS Simulator on the
same Mac machine.
From now on, the default port becomes 18182 and if it is unavailable, 
a random free port will be used. Its number will be output in the 
application log. When starting a debug session, {N} CLI will monitor 
the logs in order to receive the allocated port number for the …
=> fix(debugging): Don't close inspector socket after 30 sec. timeout

src/debugging/Inspector/Inspector/NativeScript Inspector/Communication.m, src/debugging/TNSDebugging.h, src/debugging/debugger-proxy.js
It turned out that 18182 is used by {N} CLI. It is specified as the port
to listen when launching adb server. This lead to a mysterious bug
when both android and ios devices were connected. To avoid it
for users with previous CLIs we'll change it to 18183.
For more details see:
https://github.com/NativeScript/nativescript-cli/pull/3614
=> fix(debugging): Change default debugging port to 18183

src/NativeScript/inspector/GlobalObjectConsoleClient.cpp, src/NativeScript/inspector/GlobalObjectConsoleClient.h
consoleAgent prints them correctly only when they're constructed
using the overload accepting `ScriptArguments`.
Regression has been introduced with #912
When `console.dir({a:1})` is executed by the application or in the console window of Safari Inspector the output contains only `undefined`.
`console.dir` correctly displays the object in the console window.
Fixes #930
=> fix(debugger): console.dir not displayed correctly in Safari inspector

src/debugging/TNSDebugging.h
When a second inspector client connects we want to dispose of
the previous one. Before this fix however, we only destroyed the
handler function without disconnecting the frontend socket.
When a new frontend connects, the socket of the previous one is left open.
When a new frontend connects, the socket of the previous one is closed.
Fixes #927
=> fix(debug): Close dispatch_io when disconnecting inspector

src/debugging/TNSDebugging.h
In the scenario when a new connection disconnects the previous one there's
a racing condition which sometimes leads to disconnecting both frontends.
To avoid clearing the new one when the older receives EABORT, we now
check whether the current global inspector_io matches the one of the
failed connection. This way even if the order of events is unfavoring we
won't disconnect the wrong frontend client.
Connecting a second debugger tab sometimes fails and/or makes the frontend hang.
Connecting a second debugger tab always disconnect the first one and doesn't fail sporadically.
Additional fix for #927
=> fix(debugging): Do not clear inspector if it doesn't match failed connection

cmake/CreateNativeScriptApp.cmake, src/NativeScript/CMakeLists.txt
This is necessary in order to be able to run them successfully on device
Xcode targets for sample and TestRunner apps cannot be deployed on device when NativeScript is built as a dynamic framework.
The framework is embedded in the built app bundles and they can now run on devices.
=> fix(cmake): Embed NativeScript.framework in sample and test applications

src/NativeScript/Interop.h, src/NativeScript/Interop.mm, src/NativeScript/Marshalling/Fundamentals/FFIPrimitiveTypes.cpp, src/NativeScript/Marshalling/Pointer/PointerConstructor.cpp, src/NativeScript/Marshalling/Pointer/PointerInstance.cpp, src/NativeScript/Marshalling/Pointer/PointerInstance.h, src/NativeScript/Marshalling/Pointer/PointerPrototype.cpp, src/NativeScript/Marshalling/Record/RecordConstructor.cpp, src/NativeScript/Marshalling/Record/RecordInstance.cpp, src/NativeScript/Marshalling/Record/RecordInstance.h, src/NativeScript/Marshalling/Reference/ExtVectorTypeInstance.cpp, src/NativeScript/Marshalling/Reference/IndexedRefInstance.cpp, src/NativeScript/Marshalling/Reference/IndexedRefTypeInstance.cpp, src/NativeScript/Marshalling/Reference/ReferenceConstructor.cpp, src/NativeScript/Marshalling/Reference/ReferenceInstance.cpp, src/NativeScript/Marshalling/Reference/ReferenceTypeInstance.cpp
It's possible to receive a null topCallFrame when embedding {N} runtime
in a native app. Refactor so that we take the `ExecState` as an argument
instead of relying on `vm.topCallFrame`
Fixes https://github.com/NativeScript/NativeScript/issues/6019
=> fix(marshalling): Protect against missing topCallFrame

src/NativeScript/GlobalObject.h, src/NativeScript/GlobalObject.moduleLoader.mm, src/NativeScript/inspector/GlobalObjectDebuggerAgent.mm
Continues the work from #959 which was not working with source code of CommonJS modules
=> fix(live-edit): Correctly find source of CommonJS modules in setScriptSource

examples/Gameraww/app/MasterViewController.js, src/NativeScript/JSErrors.mm
Raise an Objective C exception with JS callstack information, instead of causing
an EXC_BAD_ACCESS signal when a fatal error is detected. This way of crashing
is more appropriate for handling by error reporting analytics libraries like Sentry
refs #963
=> fix(runtime): Throw an Objective C exception on fatal error

src/NativeScript/JSErrors.h, src/NativeScript/JSErrors.mm, src/NativeScript/TNSRuntime.h, src/NativeScript/TNSRuntime.mm
The app crashes whenever an unhandled JS error is detected.
There's a new setting in `package.json` which determines whether to discard the exception after it's logged or to crash the application.
For more information see #965 and https://github.com/NativeScript/android-runtime/issues/1119
=> feat: Introduce a setting for discarding uncaught JS exceptions

src/NativeScript/Metadata/Metadata.h, src/NativeScript/ObjC/ObjCMethodCall.h, src/NativeScript/ObjC/ObjCMethodCall.mm
=> fix(objc-call): Don't crash when calling an optional protocol method

plugins/TKLiveSync/TKLiveSync.xcodeproj/project.pbxproj
I've mistakenly deleted it in #994. I thought that its contents
got included even when it was missing from TKLiveSync's project file.
=> fix(LiveSync): Add libGCDWebServer static lib to linked libraries

plugins/TKLiveSync/Podfile.lock, plugins/TKLiveSync/TKLiveSync.xcodeproj/project.pbxproj, plugins/TKLiveSync/TKLiveSync.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
* Change libGCDWebServer static lib path. With Xcode 10 it's no longer being output in a separate subdirectory
* Fix inspector build:
- Revert to using the Legacy build system
- Add missing JS_EXPORT_PRIVATE
- Remove unused variables
- Cherry-pick commits from upstream/master branch and resolve conflicts
- Unconditionally define CMSAMPLEBUFFERCALL_NOESCAPE
- Remove calls to Deprecated NSDisableScreenUpdates and NSEnableScreenUpdates
=> Fix build with Xcode 10

build/project-template/__PROJECT_NAME__.xcodeproj/project.pbxproj
The `armv7 arm64` setting is invalid when building for simulator.
The reason for not detecting it until now is that it has been
overridden with a command line argument passed to `xcodebuild`
by {N} CLI.
Doing so however prevents users from specifying their own value
for ARCHS and VALID_ARCHS settings.
See https://github.com/NativeScript/nativescript-cli/issues/4197
`VALID_ARCHS` is set in the project template's `project.pbxproj`
`VALID_ARCHS` is deleted from the project template's `project.pbxproj`.
=> fix(template): Remove VALID_ARCHS from project.pbxproj

src/NativeScript/inspector/InspectorLogAgent.cpp
Logs are not shown in Chrome console tab (#1037) 
Logs are being shown.
Implements #1037.
=> Update Devtools Log.LogEntry levels

src/NativeScript/CMakeLists.txt, src/NativeScript/Calling/FunctionWrapper.mm, tests/TestRunner/app/ApiTests.js, tests/TestRunner/app/Infrastructure/simulator.js, tests/TestRunner/app/MethodCallsTests.js, tests/TestRunner/app/index.js
* Wrap `ffi_call`s with @try-block
* Throw ObjC exception to JavaScript
(attaching the original native one as `nativeException` property)
* Update libffi with the latest master in an effort to get the
fix from https://github.com/libffi/libffi/issues/418
refs #1029
Objective-C exceptions in calls made from JS crash the application.
Objective-C exceptions are intercepted by iOS Runtime and are thrown to JS, where they can be caught. If no catch handler is found they will be treated as unhandled JavaScript exceptions.
=> fix(bridge): Catch ObjC Exceptions and throw them to JS

src/NativeScript/ObjC/ObjCMethodCallback.mm, tests/TestFixtures/TNSTestNativeCallbacks.h, tests/TestFixtures/TNSTestNativeCallbacks.m, tests/TestRunner/app/Inheritance/ProtocolImplementationTests.js
The condition for stopping the protocols loop was wrong. Add a unit test to
ensure that protocol methods from two protocols are callable from JS and native.
=> fix(bridge): Discover protocol members when extending native class

build/project-template/__PROJECT_NAME__.xcodeproj/project.pbxproj
* Add debugging and exception handling headers 
`TNSDebugging.h` and `TNSExceptionHandler.h` files have been missing
as references from the Xcode project despite being imported by `main.m`.
* Add missing xcconfig files to Xcode project 
`nativescript-build.xcconfig`, `plugins-debug.xcconfig` and `plugins-release.xcconfig`
files have been missing as references from the Xcode project despite being included
by the main configuration-specific xcconfigs.
The above listed files are missing from the `pbxproject` file despite being a part of the project
The files have been added and can be seen in the project navigator of Xcode
=> chore: Add missing xcconfigs and headers to project template

src/NativeScript/Interop.h, src/NativeScript/Interop.mm, src/NativeScript/Marshalling/Pointer/PointerConstructor.cpp, src/NativeScript/Marshalling/Pointer/PointerPrototype.cpp, tests/TestRunner/app/Marshalling/PointerTests.js
* fix(interop): Special case for pointers with address -1
The "deleted" value of WeakGCMap's hashing function is -1
and such pointer's cannot be added to the `_pointerToInstance` map.
refs #921
* fix(interop): Construct Pointer from a wrapped number
This adds support for the following syntax `interop.Pointer(new Number(number))`.
* fix(interop): Add methods `toHexString` and `toDecimalString` to Pointer
This allows for correct serialization of pointers through strings. Which can be
used for passing native objects to workers as discussed in https://github.com/NativeScript/ios-runtime/issues/620#issuecomment-449045591.
The need for these methods arises from the fact that `toNumber` can't
be used for negative pointer values, due to JavaScript's values
inability to represent very large and/or …
=> Improvements to pointer initialization and conversions to string

src/debugging/TNSDebugging.h
After the 5.1.1 releases of the CLI and the Runtime, the CLI is always sending `AttachRequest` before a debug session which is clearing the `listenSource`. In this way, the app is resumed and the `--debug-brk` flag is not working properly. 
In order to avoid that, we do not resume the app when closing the listening source anymore. It will be resumed only when a debugging client is attached or when the 30 secs timeout is reached.
=> fix: fix waitForDebugger handling

src/NativeScript/CMakeLists.txt, src/NativeScript/GlobalObject.mm, src/NativeScript/JSErrors.h, src/NativeScript/JSErrors.mm, src/NativeScript/ObjC/AllocatedPlaceholder.h, src/NativeScript/ObjC/AllocatedPlaceholder.mm, src/NativeScript/ObjC/Constructor/ObjCConstructorBase.mm, src/NativeScript/ObjC/Inheritance/ObjCClassBuilder.mm, src/NativeScript/ObjC/Inheritance/TNSDerivedClassProtocol.h, src/NativeScript/ObjC/ObjCMethodCallback.mm, src/NativeScript/ObjC/ObjCWrapperObject.h, src/NativeScript/ObjC/ObjCWrapperObject.mm, tests/TestFixtures/CMakeLists.txt, tests/TestFixtures/Interfaces/TNSClassWithPlaceholder.m, tests/TestFixtures/Marshalling/TNSAllocLog.h, tests/TestFixtures/Marshalling/TNSAllocLog.m, tests/TestFixtures/TestFixtures.h, tests/TestRunner/app/ApiTests.js, tests/TestRunner/app/ObjCConstructors.js
* Add missing `release` call in `constructObjCClass`
* Document why `AllocatedPlaceholder` can't `retain` it's wrapped instance
and why we don't call release after we create it.
* Add missing destructor call in `AllocatedPlaceholder::destroy`
* Add tests for `__releaseNativeCounterpart`
* Remove unneeded `gcProtect` call in `attachDerivedMachinery`
* fix(bridge): Remove ObjCWrapperObject from cache after dealloc
refs #1062
=>  feat(api): Provide API to release the native object wrapped by a JS one 

src/NativeScript/GlobalObject.mm, tests/TestRunner/app/ApiTests.js
* Change `jsCast` to `jsDynamicCast`
* Add tests for when the argument is not an ObjectiveC object
* Add test for checking that the JS wrapper's instance after
the release is set to `nil`
refs https://github.com/NativeScript/ios-runtime/issues/1062#issuecomment-461849820
=> fix(api): Correct argument check in __releaseNativeCounterpart

src/NativeScript/TNSRuntime+Inspector.mm, src/NativeScript/inspector/GlobalObjectConsoleClient.h, src/NativeScript/inspector/GlobalObjectInspectorController.h
`inspector_modules.js` is loaded whenever a new debugger connection is established.
When the application is built with `--bundle` however, the file is missing and debugging
is not working correctly. Log the rejection reason to the console so that errors with it don't
silently remain undetected in the future.
related to #1054, #1055, #1056, #1057
=> fix(inspector): Catch and log inspector_modules.js loading errors

README.md
Clang 4.0.1 does not support category attributes so some headers may not be parsed. Also many clang errors are thrown - for incorrectly imported headers and unavailable modules.
Metadata generator now works with llvm 7.0.0 and all clang errors are resolved.
=> chore: Update llvm to 7.0.0

src/NativeScript/GlobalObject.mm, src/NativeScript/Metadata/Metadata.h, src/NativeScript/Metadata/Metadata.mm, src/NativeScript/ObjC/Constructor/ObjCConstructorBase.mm, src/NativeScript/ObjC/Constructor/ObjCConstructorNative.mm, src/NativeScript/ObjC/Inheritance/ObjCClassBuilder.h, src/NativeScript/ObjC/Inheritance/ObjCClassBuilder.mm, src/NativeScript/ObjC/ObjCMethodCall.h, src/NativeScript/ObjC/ObjCMethodCall.mm, src/NativeScript/ObjC/ObjCMethodCallback.mm, src/NativeScript/ObjC/ObjCProtocolWrapper.mm, src/NativeScript/ObjC/ObjCPrototype.h, src/NativeScript/ObjC/ObjCPrototype.mm, src/NativeScript/TypeFactory.mm, tests/TestFixtures/Api/TNSVersions.h, tests/TestFixtures/Api/TNSVersions.m, tests/TestFixtures/Interfaces/TNSConstructorResolution.h, tests/TestFixtures/Interfaces/TNSConstructorResolution.m, tests/TestFixtures/Interfaces/TNSInheritance.h, tests/TestFixtures/Interfaces/TNSInheritance.m, tests/TestRunner/app/ApiTests.js, tests/TestRunner/app/Inheritance/InheritanceTests.js, tests/TestRunner/app/ObjCConstructors.js, tests/TestRunner/app/VersionDiffTests.js
* Filter members which are unavailable in the current SDK 
* Add `isImplementedInClass` and `isAvailableInClass` methods in
`PropertyMeta` and `MethodMeta` which additionally check whether a Class
instance supports a given optional method
* Use `isAvailableInClass` instead of `isAvailable` in `getOwnPropertyNames`
of `ObjCPrototype`, `ObjCConstructorBase`, `ObjCConstructorNative` and
in `materializeProperties` of `ObjCConstructorNative`
* Filter via `isAvailableInClass` in `BaseClassMeta`'s various
method and property getters
* Change `MembersCollection` to be a `HashSet` to avoid adding the same
member more than once when collecting them from the inheritance chain
* Remove unused functions from `BaseClassMeta`
* Add `findInterfaceMeta` function with fallback to the base interface
if the …
=> fix(runtime): Respect availability attributes for protocols and base classes

build/TestRunner.xcscheme, build/scripts/build-metadata-generator.sh, build/scripts/build-nativescript-framework.sh, build/scripts/build-testrunner-application.sh, build/scripts/common.sh, launch-c.in, launch-cxx.in, src/NativeScript/CMakeLists.txt, tests/TestFixtures/CMakeLists.txt
* Optimize TestRunner build
* Remove build command from build script
* Add custom commands in TestFixtures and NativeScript projects
for copying the built library to its expected location in `cmake-build`.
This is necessary because when building with `xcodebuild archive` the
output files are located in a different directory (located under
~/Library/Developer/Xcode/DerivedData/). It turns out that this behavior
is by design. See: https://forums.developer.apple.com/thread/53549
* Create cmake project using `cmake-gen.sh` so that TestRunner can be built
and linked
* Change archive action's configuration to `RelWithDebInfo` in scheme file
* Define `NATIVESCRIPT_XCODEPROJ` environment variable in `common.sh`
* Enable precompiled headers support of ccache
Followed instructions from …
=> chore: Speed up Jenkins build

src/NativeScript/GlobalObject.mm, src/NativeScript/ObjC/ObjCPrototype.h, src/NativeScript/ObjC/ObjCPrototype.mm, tests/TestRunner/app/ApiTests.js
Fix issue with missing `imageInsets`, `landscapeImagePhone`, `title` properties of UITabBarItem.
These properties are declared in `UIBarItem` but it actually doesn't implement them. Some of its
successors like `UITabBarItem` however do, and we need to expose them there.
This regression has been introduced with #1086 (which addressed #1084, #1085)
=> fix(runtime): Expose base class missing properties in inheritors

tests/TestRunner/app/ApiTests.js
Since the implementation of #1064 it has been made possible
for {N} users to switch on different JSC diagnostic options.
The problem was that to view the logs users had to use the Xcode
debugger, because they weren't visible in the system logs and
could not be captured by {N} CLI. With this change now all
applications that retrieve system logs from the device will process
them. We will also be able to add automated tests that ensure
these options' correct functionality.
related to #1004
=> fix(webkit): Make JSC log to system logs instead of stderr

src/NativeScript/inspector/GlobalObjectConsoleClient.cpp, src/debugging/TNSDebugging.h
1. console.trace() doesn't print stacktrace
2. Breakpoints in onNavigatingTo are not respected
1. console.trace() works as expected
2. Breakpoints are evaluated on time
Related to #1099 and #1021 .
=>  Fix breakpoints in onNavigatingTo and add stacktrace to console.trace() message

cmake/CreateNativeScriptApp.cmake, src/NativeScript/CMakeLists.txt, src/NativeScript/Metadata/Metadata.mm, src/NativeScript/ObjC/ObjCPrototype.h, src/NativeScript/ObjC/ObjCPrototype.mm, src/NativeScript/StopwatchLogger.h, tests/TestFixtures/Interfaces/TNSMethodCalls.h, tests/TestFixtures/Interfaces/TNSMethodCalls.m, tests/TestRunner/app/MethodCallsTests.js
* Patch JSC to allow for dynamic property definition during assignment
(write access)
* Make `ObjCPrototype::materializeProperties` a no op
* Make `ObjCPrototype::getOwnPropertySlot` check metadata for properties,
before searching for a method
* perf(metadata): Do not scan for property overloads
Properties cannot have "JS overloads" in base classes as methods do
and there's no need to traverse the hierarchy. JS overloads are methods
with different selectors and number of arguments which have the same jsName
=> perf(runtime): Lazy evaluation of properties

CMakeLists.txt, build/scripts/build-nativescript-framework.sh, build/scripts/build-testrunner-application.sh, cmake/BuiltArtifactToTargetDestination.cmake, cmake/PrecompiledHeaders.cmake, launch-c.in, launch-cxx.in, src/NativeScript/CMakeLists.txt, tests/TestFixtures/CMakeLists.txt
Otherwise all NativeScript source files are rebuilt everytime when the
PCH file is regenerated. Which is done on every build.
* Disable precompiled headers when using CCache and suppress `nonportable-include-path` warning which occcurs with disabled precompilation. Fixing the code is beyond this PR's scope.
* Extract CMake macros for duplicated logic: `CopyBuiltArtifactToTargetDestinationIfDifferent` and `PostBuildCopyIfDestDifferentThanSrc `
* Play nicely and do not redefine CCACHE environment variables if they are already set from outside
* Optimize TestRunner build
=> chore(build): Disable precompiled headers when using ccache

build/scripts/build-step-metadata-generator.py
Metadata generator's stderr output has always been redirected into a file
in the `platforms/ios/build/<Configuration>` directory but this has not been
documented so far and has remained quite invisible to {N} users. It's
contents however can be extremely helpful in detecting issues with
missing metadata in cases like the one in #1117
* Copy stderr text file to TNS_DEBUG_METADATA_PATH alongside all yamls
* Add messages in metadata generations output so that it becomes a bit more
visible that such a file actually exists
* Revert "fix: Ignore includeNotFoundErrors in order to keep visiting the entire AST"
It seems that emitting such errors doesn't change the number of
generated metadata items. Omitting them, however, can hide source
code issues that prevent some entities' metadata from being …
=> fix(metadata): Copy stderr log to yaml dir

build/scripts/build-metadata-generator.sh, build/scripts/build-step-metadata-generator.py
Also add diagnostic output to stderr stream and enable it by default
in `build-step-metadata-generator.py`
This option is still needed in some cases and I couldn't find a way to disable it.
These are the issues we've run into with its disabling so far:
* In Objective-C mode level-db framework breaks parsing because it includes
c++ headers without checking whether the compiler is in C++ mode
* In Objective-C++ mode many issues occurred. Some of them might be circumventable
but the one which made me discard the effors was that enums are lost due to the
following definition taken from CoreFoundation:
```
#if (__cplusplus)
#define CF_OPTIONS(_type, _name) _type _name; enum __CF_OPTIONS_ATTRIBUTES : _type
#else
#define CF_OPTIONS(_type, _name) enum __CF_OPTIONS_ATTRIBUTES _name : _type _name; …
```
=> fix(metadata): Ressurrect "includeNotFoundErrors" option of CLang

src/NativeScript/GlobalObject.h, src/NativeScript/GlobalObject.mm, src/NativeScript/ObjC/ObjCPrimitiveTypes.mm, tests/TestRunner/app/ApiTests.js, tests/TestRunner/app/ObjCConstructors.js
When an Objective C class is read and there is no metadata for it we are getting the constructor from the first of its parents that have metadata.
When there's no metadata for a given Objective C class we are returning a wrapped object instead of it's parent constructor. 
Related to #1120
=> fix: return WrappedObject for classes with no meta

src/NativeScript/Metadata/Metadata.h, src/NativeScript/Metadata/Metadata.mm, src/NativeScript/ObjC/ObjCMethodCallback.mm
Getting a unicode property's value will fail (or crash in debug):
```
let obj = NSObject.alloc().init();
obj.Ł = "Ł";
console.log(obj.Ł);
```
This is caused by the following ASSERT in WebKit:
```
ALWAYS_INLINE const LChar* characters8() const { ASSERT(is8Bit()); return m_data8; }
```
In general using characters8() may lead to unexpected behavior as [here](https://github.com/NativeScript/NativeScript/issues/7120)
Unicode properties work as expected.
Fixes: https://github.com/NativeScript/NativeScript/issues/7120
=> fix: Unicode properties

src/NativeScript/smartStringify.js
Related to https://github.com/NativeScript/android-runtime/issues/1358
Avoid memory leak by adding `const` before the `seen` variable to use local variable.
=> added const to avoid using `seen` as global

build/project-template/internal/nsld.sh
nsld.sh script always calls $TOOLCHAIN_DIR/usr/bin/clang.
Introduce new NS_LD variable that can point to an alternate linker that user wants to use. If not set - then we call the default one.
=> Add NS_LD variable to be used for alternate linker

build/npm/inspector_package.json, build/npm/runtime_package.json, src/NativeScript/ObjC/TNSArrayAdapter.mm, src/NativeScript/ObjC/TNSDataAdapter.mm, src/NativeScript/ObjC/TNSDictionaryAdapter.mm, src/NativeScript/TNSRuntime.mm
* `TNSArrayAdapter`, `TNSDataAdapter` and `TNSDictionaryAdapter` hold `Strong`
references to their underlying JS objects. When the Objective-C instances of these
classes were `dealloc`-ed, these references' destructors were being called outside
of the JSC VM's lock which lead to nasty and rarely occurring crashes when such
adapters are being used in threads different than the main thread of the JSC engine.
* Do not store `ExecState`s as calls to an adapter can be made long after the JS
state has changed. Use global object's `globalExec` instead.
* Reset `Strong` handles inside the locked section. This way the C++ destructor
of a nullptr handle will not have to modify anything in the VM's heap.
* Dump the native and JavaScript callstacks when any
of SIGABRT SIGILL, SIGSEGV, SIGFPE or …
=>  fix(bridge): Synchronize access to Strong handles in collection adapters

src/NativeScript/Metadata/Metadata.mm, src/NativeScript/Workers/WorkerMessagingProxy.mm
Each worker task should have its own autorelease pool so that
objects don't remain in memory throughout the whole worker's
lifetime.
Cache result in getSystemVersion - this caching has been broken with https://github.com/NativeScript/ios-runtime/commit/850e5e45794db79c5d3a35fe0af7c8542fc8d528#diff-d14ec105c5ba1de0835c6d67c97a4ef6
refs #1137
=>  fix(workers): Objective-C autoreleased objects leak 

src/NativeScript/TNSRuntime.mm
After introducing our signal handler crashes have stopped being
detected by Firebase. Uninstall our handler and re-send the signal so that
the app crashes instead of exits.
ref https://github.com/NativeScript/ios-runtime/issues/1137#issuecomment-498586218
=> fix(runtime): Resend handled signal instead of exitting

CHANGELOG.md
Here they are randomly ordered and this causes https://github.com/NativeScript/ios-runtime/issues/1158.
All sources will be sent by NativeScript on debugger enable event in
`GlobalObjectDebuggerAgent::enable()` and the order there will be the
correct one because they are taken from module loader's registry.
refs #1158
=> fix(jsc): Do not send source parsed events on attach.

build/project-template/internal/nsld.sh
Xcode 10.2 generates the final merged `-Swift.h` file some time
after invoking the linker. Instead of that header we now
find and use the one generated for the current architecture.
It is emitted before the linker has been started.
refs #1166
**Additional info**
The three bridging headers that get generated for a simulator build  are:
```
platforms/ios/build/TestApp.build/Debug-iphonesimulator/TestApp.build/Objects-normal/i386/TestApp-Swift.h
platforms/ios/build/TestApp.build/Debug-iphonesimulator/TestApp.build/Objects-normal/x86_64/TestApp-Swift.h
platforms/ios/build/TestApp.build/Debug-iphonesimulator/TestApp.build/DerivedSources/TestApp-Swift.h
```
We're now finding and using the one for the currently linked architecture from `Objects-normal`,
while previously we used the merged one in …
=> fix(project-template): Find Swift bridging header when building metadata

build/project-template/__PROJECT_NAME__.xcodeproj/project.pbxproj, build/project-template/internal/nsld.sh
* Swift bridging header was not being detected correctly when
there are spaces in the path
* Parse the `-arch` command line argument, instead of relying on
the timestamp to find out the correct architecture-specific bridging
header. Timestamp yielded incorrect results because:
1) it has 1 second precision and
2) even if it was precise it would still be unreliable because
headers may have been created by a previous build
=> fix(project-template): Correct metadata when path contains spaces

src/NativeScript/Metadata/Metadata.h, src/NativeScript/Metadata/Metadata.mm, src/NativeScript/ObjC/Constructor/ObjCConstructorBase.mm, src/NativeScript/ObjC/Inheritance/ObjCClassBuilder.mm, src/NativeScript/TypeFactory.mm, tests/TestFixtures/Interfaces/TNSInheritance.h, tests/TestFixtures/Interfaces/TNSInheritance.m, tests/TestRunner/app/ApiTests.js, tests/TestRunner/app/Inheritance/InheritanceTests.js
Fix issues with `instenceof` operator returning `false`
for even public types which were being returned as `id<Proto>`
which arose with #1175
* Do not state unknown class and additional protocols in the
constructor functions' names. This lead to errors in the Firebase
plugin which relies heavily on class names to do object conversions.
* Remove redundant entries from additional protocols list before
creating a separate constructor function
* Add the pure class' constructor function to the inheritance hierarchy
of any additional constructor function (having additional protocol(s) or
wrapping an unknown private class)
* Extract `forEachProtocol` helper method
* Add unit tests
=> fix(runtime): Constructor functions' hierarchy

build/project-template/internal/nsld.sh
Xcode 11 doesn't specify an `-arch` argument but uses `-target` instead
=> fix(project-template): Correctly get architecture in `nsld` with Xcode 11

src/NativeScript/JSErrors.mm, tests/TestRunner/app/ApiTests.js, tests/TestRunner/app/StackTraceTests.js, tests/TestRunner/app/index.js
Related to #1135
Added support for Error.prepareStackTrace method similar to the one in V8 and changed the format of the stack trace to be the same as android (also as node and browsers) with ```at ...```
=> feat: Error.prepareStackTrace method support

examples/Gameraww/app/DetailViewController.js, src/NativeScript/ObjC/ObjCMethodCallback.mm, tests/TestRunner/app/Inheritance/InheritanceTests.js
* Override `prefersStatusBarHidden` property with a JS property instead of a function
* Improve error handling and throw an exception when property is being overridden with a function
* Add unit tests for thrown exceptions when a property is being wrongly overridden
=> chore(Gameraww): Fix crash on startup

src/debugging/TNSDebugging.h
Currently CLI performs an additional application start when sending refresh notification to the application. The purpose of this additional application start is to ensure that the application will be started when sending the notification no matter if it is currently crashed. However, this additional operation slows down the entire livesync process with around 2-3 seconds per change. The purpose of this PR is to eliminate the delay as posting `AppRefreshStarted` notification from application. CLI starts an observer notification in order to check if the `AppRefreshStarted` will be sent from the application. In case it is sent, CLI refreshes the application via `RefreshRequest` notification. In case a such notification is not sent, CLI restarts the application in 3 seconds (this is the …
=> fix: notify for AppRefreshStarted and remove the log for successful refresh request

src/MetadataGenerator.cmake
* Catalyst SDK crashes
* Exclude circular dependant types when some subtype is not supported
* `isStaticFramework` check when linked libraries are set explicitly
* Add integration tests
refs #1197, t1426491
=> fix: Metadata generator crashes

CHANGELOG.md, README.md, src/NativeScript/ObjC/TNSExceptionHandler.h, src/NativeScript/TNSRuntime.mm
* Do not attempt to use runtime object if `[TNSRuntime current]`
returns `nullptr`.
* Update CHANGELOG for v6.1.0
=>  fix(runtime): null pointer dereference in signal and unhandled exception handlers

CHANGELOG.md, src/NativeScript/JSErrors.mm, src/debugging/TNSDebugging.h
* **fix(debugging): Improve user experience when app crashes in debugger**
* Log exceptions the same way as outside of debugger
* Additionally warn that app is being kept alive on purpose
* Drop locks before entering loop so that expression evaluation
continues to work
* Stop loop when debugger detaches
* **fix(debugging): Dispatch messages to global GCD queue**
Incoming debugger messages could cause a breakpoint to be
triggered (e.g. invalid evaluation expression with break on
exceptions turned on). We deadlocked when we didn't dispatch
them and didn't release the current thread, because no other
debugger message could be processed.
refs #1200, #1201
=>  fix(debugging): Improve user experience when app crashes and dispatch messages to GCD

CHANGELOG.md, build/project-template/internal/nativescript-build.xcconfig
When C++ source files are present in the project the
build system uses LDPLUSPLUS instead of LD
refs #1203
=> fix(project-template): Add LDPLUSPLUS variable

src/NativeScript/Marshalling/Fundamentals/FFIPrimitiveTypes.cpp, tests/TestFixtures/Marshalling/TNSPrimitivePointers.m, tests/TestRunner/app/Infrastructure/utf8.js, tests/TestRunner/app/Marshalling/ReferenceTests.js, tests/TestRunner/app/index.js
* [Marshalling] Change underlying type of returned references from `int8` to `uint8`
* [TestFixtures] Use `stringWithUTF8String` instead of formatting with
`%s` (which uses system default encoding)
* [TestRunner] Add `utf8` node module to TestRunner project
* [TestRunner] Add a test with cyrillic characters which validates
that references are indeed unsigned
refs #1196
=> fix(marshalling): Expose C strings as references to uint8 in JS

src/NativeScript/ObjC/Constructor/ObjCConstructorBase.mm, tests/TestRunner/app/Inheritance/TypeScriptTests.js, tests/TestRunner/app/Inheritance/TypeScriptTests.ts, tests/TestRunner/app/Marshalling/ReferenceTests.js, tests/TestRunner/app/tsconfig.json
* fix(JSC): Use `SuspendExceptionScope` instead of clearing exception
* fix(runtime): Do not call initializer if `alloc` throws a JS exception
* Add tests for erroneous TS extends
* Add `tsconfig.json` and transpile `TypeScriptTests.ts`
Exceptions raised during TS extends call are lost and errors are difficult to detect.
Exceptions raised during TS extends call are correctly thrown in JS and can be processed in a catch block or unhandled exception handler, or crash with a meaningful error.
=> fix(runtime): Do not lose exception in TS extends

src/NativeScript/CMakeLists.txt, src/NativeScript/GlobalObject.mm, src/NativeScript/Metadata/Metadata.h, src/NativeScript/Metadata/Metadata.mm, src/NativeScript/Metadata/MetadataInlines.h, src/NativeScript/ObjC/Constructor/ObjCConstructorNative.mm, src/NativeScript/ObjC/ObjCPrototype.mm, src/NativeScript/TypeFactory.h, src/NativeScript/TypeFactory.mm, tests/TestFixtures/CMakeLists.txt, tests/TestFixtures/Interfaces/TNSSwiftLike.h, tests/TestFixtures/Interfaces/TNSSwiftLike.m, tests/TestFixtures/TestFixtures.h, tests/TestRunner/app/MetadataTests.js
Querying metadata for Objective-C interfaces and protocols should
not be done by the JS name when the string we search for is actually
their native name
* Introduce 2 additional global tables in metadata for Interfaces and Protocols
indexed by their native name
* Make `Metadata::GlobalTable` a template struct and move its implementation
to `MetadataInlines.h`
* Use the correct global table depending on the name and entity being looked up
* Add unit test with an `objc_runtime_name` attribute emulating that it's been
generated by the Swift compiler
refs #712
=> fix(runtime): Lookup into native MD tables when searching by name

src/NativeScript/inspector/GlobalObjectInspectorController.cpp, src/NativeScript/inspector/GlobalObjectInspectorController.h, src/NativeScript/inspector/InspectorPageAgent.mm
Move the logic from core modules to iOS runtime. This way watches
and expressions evaluation in console will work for apps which
do not use the core modules (e.g. TestRunner of iOS runtime):
* Send `executionContextCreated` event when PageAgent is enabled
* Add dummy implementation for `Runtime.compileScript` message
refs #905
Merge along with https://github.com/NativeScript/NativeScript/pull/8072
=> refactor(debugging): Chrome DevTools Runtime domain logic

build/project-template/__PROJECT_NAME__.xcodeproj/project.pbxproj
Otherwise, they ended up being included in the app bundle.
The following files have been removed from the app target in the project template:
* nativescript-pre-build
* nativescript-post-build
* nativescript-pre-link 
* strip-dynamic-framework-architectures.sh 
* nsld.sh
_**Note** To avoid regressing this, we should add integration tests that verify that no unexpected files appear in the built app bundles!_
=> fix(project-template): Remove build scripts from target

plugins/TKLiveSync/Podfile.lock, src/NativeScript/ObjC/Inheritance/ObjCClassBuilder.mm, src/NativeScript/ObjC/ObjCPrototype.mm, tests/TestFixtures/Interfaces/TNSMethodCalls.h, tests/TestFixtures/Interfaces/TNSMethodCalls.m, tests/TestRunner/app/Inheritance/InheritanceTests.js
A property can be defined from both a protocol and a base class.
Currently, the protocol definition takes precedence but there are
cases in which the other way around is correct.
* (ObjCPrototype) Check the property descriptor of the base class and
don't define it if the base one has more accessors.
* (ObjCClassBuilder) When defining a property check for metadata both
with and without considering protocols. Use the one with more accessors.
* Add unit tests
refs #1223
=> fix(runtime): Do not hide property with more accessors

src/NativeScript/inspector/InspectorPageAgent.mm
Chrome DevTools requires `origin` to be set to the frame identifier.
Fix regression from #1222
When `origin` was missing, the `Console` tab in Chrome Dev Tools was not being loaded successfully.
=> fix(debugging): Add origin parameter to ExecutionContextDescription

src/NativeScript/ObjC/ObjCPrototype.h, src/NativeScript/ObjC/ObjCPrototype.mm, tests/TestRunner/app/Inheritance/InheritanceTests.js
Extract logic for checking whether a property defined in a class should be left
to be handled by its base class via the prototype chain or not. Apply the same
logic when collecting own property names and exclude them if needed.
Properties that are hidden from derived classes are still reported by `Object.getOwnPropertyNames`. I.e. 
`Object.getOwnPropertyDescriptor` could return `undefined` for some of the properties returned 
by `Object.getOwnPropertyNames`.
Properties that are hidden from derived classes are omitted by `Object.getOwnPropertyNames` as well.
regressed after #1226
=> fix(runtime): Exclude duplicate properties from getOwnPropertyNames' result

src/NativeScript/Metadata/Metadata.h, src/NativeScript/TypeFactory.h, src/NativeScript/TypeFactory.mm
* Check cache before looking up metadata when searching
for a constructor by Objective-C class
* Do not retrieve `deepProtocolsSet` when no additional protocols
are passed
* (metadata-generator) Increase number of buckets in GlobalTables
=> perf: Optimize metadata lookup by native name

build/scripts/build-step-metadata-generator.py
Respect and pass `-fmodules` flag to metadata generator when
clang modules support is enabled in the application
Metadata generator never uses `-fmodules`.
Metadata generator will use `-fmodules` when modules support is enabled
refs #1233
=> fix(metadata-generator): Respect CLANG_ENABLE_MODULES

build/project-template/__PROJECT_NAME__.xcodeproj/project.pbxproj
The `disable_automatic_code_signing` method in `fastlane` fails with: `Seems to be a very old project file format - please open your project file in a more recent version of Xcode`
The project can be processed by the `fastlane` tools.
=> fix: make the pbxproject fastlane compatible

src/NativeScript/JSErrors.mm
The value is wrongly read as `false` when the current thread
doesn't have a `TNSRuntime` object associated with it. Instead of
calling `[TNSRuntime current]` use `[TNSRuntime runtimeForVM:]`
which will correctly find the object that matches the current
execution state.
=> fix(runtime): Correctly retrieve discarded exceptions flag

build/project-template/__PROJECT_NAME__.xcodeproj/project.pbxproj
The CLI is not handling these settings when building with `--provision`.
`tns build ios --provision X --for-device` is failing.
Regression by: https://github.com/NativeScript/ios-runtime/pull/1240
=> fix: wrong automatic signing configuration

src/NativeScript/JSErrors.h, src/NativeScript/Metadata/Metadata.h, src/NativeScript/Metadata/MetadataInlines.h, src/NativeScript/TypeFactory.mm, tests/TestFixtures/Interfaces/TNSSwiftLike.h, tests/TestFixtures/Interfaces/TNSSwiftLike.m, tests/TestRunner/app/MetadataTests.js
* fix(metadata-generator): Typings generation of functions
* fix(runtime): Throw a native exception in `parseType` 
* fix: Register Swift classes with both native names 
* Update the `metadata-generator` submodule
* Add an optional demangled name for every metadata entity
* Add a test case with a nested Swift-like class
refs #1251
=> fix: Register Swift classes with both native names 

CHANGELOG.md, build/npm/runtime_package.json, src/debugging/TNSDebugging.h
Multiple dispatch_io operations are usually running
simultaneously. When recreating the inspector listening
socket after an "AttachRequest" notification from {N} CLI,
the following crash happened in a dispather worker thread:
`BUG IN CLIENT OF LIBDISPATCH: Unexpected EV_VANISHED (do not destroy random mach ports or file descriptors)`
The reason turned out to be that we always have at least 2 pending
current operations. One is reading the next message,
and the other one -- the cleanup handler from `dispatch_io_create`.
refs #1254
=> fix(debugging): Do not close data socket prematurely

src/NativeScript/SymbolLoader.mm, tests/TestRunner/app/ApiTests.js
* Use NSBundle to load bundles instead of `CFBundleLoadExecutable`
* Do not attempt load a bundle more times than it is needed
* Unload the bundle if its state was previously unloaded. Sometimes
framework bundles use resource bundles of the same name and keeping
the framework loaded breaks them. OTH, loading and unloading a framework
bundle is sufficient for its executable code to be registered with the
Objective-C runtime.
refs #1252
=> fix(runtime): Unload frameworks in SymbolLoader::load

tests/TestRunner/app/MetadataTests.js
Since iOS 13.4 `object_getClassName` and similar functions have started 
returning the mangled Swift class names instead of the demangled ones
that previous versions did.
=> tests: Fix expectation for Swift mangled names

src/NativeScript/GlobalObject.mm, src/NativeScript/ObjC/ObjCTypes.mm, tests/TestFixtures/Interfaces/TNSInheritance.m, tests/TestRunner/app/Inheritance/InheritanceTests.js
Classes that don't inherit from `NSObject` (or any other class with metadata)
cause an infinite loop in `GlobalObject::constructorFor`. Treat such classes
as inheriting from `NSObject` as a best effort to support them.
refs support ticket 1464280
=> fix(runtime): Private root classes cause infinite loop
